'use strict';
process.env.NODE_ENV='test';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),ExcelJS=require('exceljs');
const {DatabaseSync}=require('node:sqlite');
const {spawnSync}=require('node:child_process');
const testDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'wing-test-center-'));
process.env.HOST='127.0.0.1';process.env.PORT='18080';process.env.BASE_URL='http://127.0.0.1:18080';process.env.APP_SECRET='automated-test-secret';process.env.DB_FILE=path.join(testDirectory,'automated-test.db');process.env.SEED_DEMO_DATA='false';
process.env.FRONTEND_MODE='htmx';
const production=require('./server');
const {server,db,signedQr}=production;
const crypto=require('node:crypto');
if(db.prepare('SELECT COUNT(*) n FROM users').get().n!==1||db.prepare('SELECT COUNT(*) n FROM participants').get().n||db.prepare('SELECT COUNT(*) n FROM test_cases').get().n)throw Error('Fresh startup must contain admin only');
const addFixture=db.prepare('INSERT INTO participants(code,name,type) VALUES(?,?,?)');
for(let i=1;i<=30;i++)addFixture.run((i<=20?'A':'B')+String(i<=20?i:i-20).padStart(2,'0'),'Fixture '+i,i<=20?'AGENT':'BRANCH');
for(const [name,password,role,pid] of [['qalead','QA@123','QA_LEAD',null],['tech','Tech@123','TECH',null],['agent01','Agent@123','AGENT',1],['branch01','Branch@123','BRANCH',21]])db.prepare('INSERT INTO users(username,password_hash,role,display_name,participant_id) VALUES(?,?,?,?,?)').run(name,crypto.pbkdf2Sync(password,'ptc-v1',120000,32,'sha256').toString('hex'),role,name,pid);
const {parseProductionWorkbook}=require('./lib/production-workbook');
const {backupDatabase,replaceProductionData}=require('./lib/production-replacement');
const base='http://127.0.0.1:18080';
async function login(username,password){const r=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})}),d=await r.json();if(r.status!==200)throw Error('Login failed for '+username+': '+JSON.stringify(d));return {cookie:r.headers.get('set-cookie').split(';')[0],setCookie:r.headers.get('set-cookie'),csrf:d.user.csrf,user:d.user}}
async function jsonRequest(url,{auth,method='GET',body,headers={}}={}){const h={...headers};if(auth){h.Cookie=auth.cookie;h['X-CSRF-Token']=auth.csrf}if(body&&!Buffer.isBuffer(body)&&typeof body!=='string'){h['Content-Type']='application/json';body=JSON.stringify(body)}const r=await fetch(base+url,{method,headers:h,body}),d=await r.json().catch(()=>({}));return {r,d}}
async function workbookBuffer(rows){const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('Cash Xpress -Master Agent');sheet.addRows([[],[],[],['No','Priority Level','Channel','Case Type','Scenario','Account Type','Sender Account#','Currency','CoS','Amount Cash In','Customer Fee (Agent Collect Cash)','Agent Collect cash from Customer','Sender Amount (WCX)','Wing Revenue','Commission (WCX)','Exchange Rate','Rate Type','Account Type Receiver','Receiver Account','Receiver Currency','Receiver CoS','Receiver Amount','TID','Hash','Expected Result','Actual Result','Status','Date','Tester','QA Remark','Jira Link','Finance Status','Finance Remark','Case ID','Participant Code'],...rows]);return Buffer.from(await workbook.xlsx.writeBuffer())}
function cssBlock(source,header){const start=source.indexOf(header);if(start<0)throw Error('Missing CSS block: '+header);const open=source.indexOf('{',start);let depth=0;for(let index=open;index<source.length;index++){if(source[index]==='{')depth++;else if(source[index]==='}'&&--depth===0)return source.slice(open+1,index)}throw Error('Unclosed CSS block: '+header)}
function requireCss(source,expected,context){for(const rule of expected)if(!source.includes(rule))throw Error('Missing '+context+': '+rule)}
function realRows(){return [
 [1,'Priority 1','WCX POS','Positive','Perform Bakong Cash-In','PSP','04485572','KHR','Cash Xpress -Master Agent',400100,5200,405300,403700,3600,1600,'N/A','N/A','Other Bank','Bakong Wallet','KHR','Bakong',400100,'FYC667336','e5f015f7','Service succeeds','As Expected Result','Passed\u200b',new Date('2026-09-04'),'Ratha Tounh','Currency missing',null,'Not Verify Yet',null,'WCX-001','A01'],
 [2,'Priority 1','WCX eKYC','Positive','Perform Bakong Cash-In eKYC','PSP','04485587','USD','Cash Xpress -Master Agent',100.01,1.3,101.31,100.91,0.9,0.4,'N/A','N/A','Other Bank','Bakong Wallet','USD','Bakong',100.01,'FYC667361','1d0c7522','Service succeeds','Unexpected fee','Failed',new Date('2026-09-04'),'Ratha Tounh','Investigate fee','https://jira.example/WCX-2','Verified',null,'WCX-002','B01']
 ]}
async function run(){
 const pos=await parseProductionWorkbook(fs.readFileSync('/Users/sam/Downloads/1.1 Channel- WCX POS.xlsx'),{channel:'WCX POS',fileName:'1.1 Channel- WCX POS.xlsx'}),ekyc=await parseProductionWorkbook(fs.readFileSync('/Users/sam/Downloads/3.1 Channel WCX-Ekycy.xlsx'),{channel:'WCX eKYC',fileName:'3.1 Channel WCX-Ekycy.xlsx'});if(pos.records.length!==530||ekyc.records.length!==270)throw Error('Production row reconciliation failed: '+pos.records.length+'/'+ekyc.records.length);if(pos.excludedSheets.join('|')!=='WCX eKYC|Wingpay'||ekyc.excludedSheets.join('|')!=='WCX eKYC|Wingpay')throw Error('Reference worksheets were not excluded');if(!pos.records.some(x=>x.productionStatus==='NOT_EXECUTED')||!pos.records.some(x=>x.durableKey.includes('::')))throw Error('Production parser did not normalize statuses or durable keys');if(new Set(pos.records.map(x=>x.durableKey)).size!==530||new Set(ekyc.records.map(x=>x.durableKey)).size!==270)throw Error('Production durable keys are not unique');
 const testCaseColumns=db.prepare('PRAGMA table_info(test_cases)').all().map(x=>x.name),assignmentInfo=db.prepare('PRAGMA table_info(assignments)').all(),assignmentColumns=assignmentInfo.map(x=>x.name);for(const column of ['channel','case_type','source_sheet','subcategory','source_case_id','durable_key'])if(!testCaseColumns.includes(column))throw Error('Missing test_cases migration: '+column);for(const column of ['tester','executed_at','qa_remark','jira_link','finance_status','finance_remark','source_details_json','production_status','workflow_state','source_case_id'])if(!assignmentColumns.includes(column))throw Error('Missing assignments migration: '+column);if(assignmentInfo.find(x=>x.name==='participant_id').notnull!==0)throw Error('participant_id must allow unassigned production cases');if(typeof production.normalizeProductionStatus!=='function')throw Error('normalizeProductionStatus is missing');const expectedStatuses={'passed':'PASSED','failed':'FAILED','pending':'PENDING','dependency':'DEPENDENCY','not executed':'NOT_EXECUTED','ncfl':'NCFL','production test':'PRODUCTION_TEST','production bug':'PRODUCTION_BUG','n/a':'NOT_APPLICABLE','in progress':'IN_PROGRESS','stage test':'STAGE_TEST'};for(const [input,want] of Object.entries(expectedStatuses))if(production.normalizeProductionStatus(input+'\u200b')!==want)throw Error(input+' status normalization failed');
 const userIndexes=db.prepare("SELECT name,sql FROM sqlite_master WHERE type='index' AND tbl_name='users'").all();if(userIndexes.some(x=>x.name==='idx_users_participant_login'))throw Error('Legacy participant login index still exists');if(!userIndexes.some(x=>x.name==='idx_users_participant_role_login'&&x.sql.includes("role IN ('AGENT','BRANCH')")))throw Error('Participant role login index is missing');if(userIndexes.some(x=>x.name==='idx_users_observer_login'))throw Error('Legacy Observer index remains');if(!db.prepare("SELECT name FROM sqlite_master WHERE name='observer_participants'").get())throw Error('Observer relationship missing');
 const legacy=db.prepare("INSERT INTO test_cases(case_code,title,process) VALUES('LEGACY-CHECK','Legacy','Legacy') RETURNING id,channel").get();if(legacy.channel!=='Uncategorized')throw Error('Legacy channel default failed');db.prepare('DELETE FROM test_cases WHERE id=?').run(legacy.id);
 let {r,d}=await jsonRequest('/api/dashboard');if(r.status!==401)throw Error('Dashboard must require authentication');
 const admin=await login('admin','Admin@123');
 ({r,d}=await jsonRequest('/api/dashboard',{auth:admin}));if(r.status!==200||d.total!==0||d.channels.length!==0)throw Error('New database should be empty by default: '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/users',{auth:admin}));if(r.status!==200||d.items.some(x=>x.password_hash))throw Error('Safe user list failed');
 ({r,d}=await jsonRequest('/api/users',{auth:admin,method:'POST',body:{username:'short-manager',password:'x',role:'MANAGER',displayName:'Short Password Manager'}}));if(r.status!==201)throw Error('Any non-empty Manager password should be accepted: '+JSON.stringify(d));await login('short-manager','x');
 ({r,d}=await jsonRequest('/api/users',{auth:admin,method:'POST',body:{username:'word-agent',password:'word',role:'AGENT',displayName:'Word Password Agent',participantId:2}}));if(r.status!==201)throw Error('Any non-empty Agent password should be accepted: '+JSON.stringify(d));await login('word-agent','word');
 ({r,d}=await jsonRequest('/api/users',{auth:admin,method:'POST',body:{username:'observer-a02',password:'o',role:'OBSERVER',displayName:'Observer A02',participantId:2}}));if(r.status!==201)throw Error('Observer creation failed: '+JSON.stringify(d));const observer=await login('observer-a02','o');if(observer.user.role!=='OBSERVER'||observer.user.participantId)throw Error('Observer participant link missing');
 ({r,d}=await jsonRequest('/api/users',{auth:admin,method:'POST',body:{username:'observer-a02-duplicate',password:'o',role:'OBSERVER',displayName:'Duplicate Observer',participantId:2}}));if(r.status!==409)throw Error('Duplicate Observer participant link was accepted');
 ({r,d}=await jsonRequest('/api/users',{auth:admin,method:'POST',body:{username:'observer-unlinked',password:'o',role:'OBSERVER',displayName:'Unlinked Observer'}}));if(r.status!==201)throw Error('Empty Observer creation failed');const emptyObserver=await login('observer-unlinked','o');({r,d}=await jsonRequest('/api/observer/testers',{auth:observer}));if(r.status!==200||d.items.length!==1||d.items[0].id!==2)throw Error('Observer tester overview missing');({r,d}=await jsonRequest('/api/observer/testers',{auth:emptyObserver,method:'POST',body:{participantId:2}}));if(r.status!==409)throw Error('Observer stole tester');
 ({r,d}=await jsonRequest('/api/users',{auth:admin,method:'POST',body:{username:'empty-password',password:'',role:'MANAGER',displayName:'Empty Password'}}));if(r.status!==400)throw Error('Empty passwords must be rejected');
 ({r,d}=await jsonRequest('/api/users',{auth:admin,method:'POST',body:{username:'manager1',password:'Manager@12345',role:'MANAGER',displayName:'Test Manager'}}));if(r.status!==201)throw Error('Manager creation failed: '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/users',{auth:admin,method:'POST',body:{username:'display1',password:'Display@12345',role:'DISPLAY',displayName:'Management TV'}}));if(r.status!==201)throw Error('Display creation failed: '+JSON.stringify(d));
 const participantLogin=await login('agent01','Agent@123');if(participantLogin.user.participantId!==1)throw Error('Seeded Agent login is not linked to its participant');
 const branchLogin=await login('branch01','Branch@123');if(branchLogin.user.participantId!==21)throw Error('Seeded Branch login is not linked to its participant');
 const manager=await login('manager1','Manager@12345'),display=await login('display1','Display@12345');if(!/Max-Age=604800/.test(display.setCookie))throw Error('Display session is not seven days');
 const xlsx=await workbookBuffer(realRows());
 ({r,d}=await jsonRequest('/api/test-cases/import-xlsx',{auth:admin,method:'POST',body:xlsx,headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}}));if(r.status!==200||d.insertedCases!==2||d.assignmentsCreated!==2||d.channels.length!==2)throw Error('XLSX import failed: '+r.status+' '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/test-cases/import-xlsx',{auth:admin,method:'POST',body:xlsx,headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}}));if(r.status!==200||d.updatedCases!==2||d.assignmentsUpdated!==2)throw Error('Repeat import did not upsert: '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/dashboard',{auth:manager}));if(r.status!==200||d.total!==2||d.completed!==1||d.failed!==1||d.channels.map(x=>x.channel).join(',')!=='WCX eKYC,WCX POS'||d.channels[1].completionPercent!==100||!d.lastUpdated)throw Error('Channel dashboard failed: '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/dashboard',{auth:display}));if(r.status!==200)throw Error('Display cannot read dashboard');
 ({r,d}=await jsonRequest('/api/test-cases?channel=WCX%20POS',{auth:admin}));if(r.status!==200||d.items.length!==1||d.items[0].channel!=='WCX POS')throw Error('Channel case list failed');
 const agent=await login('agent01','Agent@123');({r,d}=await jsonRequest('/api/my-assignments?channel=WCX%20POS',{auth:agent}));if(r.status!==200||d.items.length!==1||d.items[0].channel!=='WCX POS'||!d.items[0].source_details)throw Error('Channel assignment queue failed: '+JSON.stringify(d));
 const qa=await login('qalead','QA@123');({r,d}=await jsonRequest('/api/defects?channel=WCX%20eKYC',{auth:qa}));if(r.status!==200||d.items.length!==1||d.items[0].channel!=='WCX eKYC'||d.items[0].finance_status!=='Verified')throw Error('Channel defect queue failed: '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/dashboard',{auth:qa}));if(r.status!==200)throw Error('QA Lead cannot read Management TV dashboard');
 ({r,d}=await jsonRequest('/api/tv/participants?type=AGENT'));if(r.status!==401)throw Error('Participant TV API must require authentication');
 ({r,d}=await jsonRequest('/api/tv/participants?type=AGENT',{auth:admin}));if(r.status!==200||d.assignedCases!==1||d.submittedCases!==1||d.doneParticipants!==1||d.testingParticipants!==0||d.items.length!==1||d.items[0].status!=='Done'||d.items[0].progressPercent!==100)throw Error('Admin Agent TV summary failed: '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/tv/participants?type=BRANCH',{auth:qa}));if(r.status!==200||d.items.length!==1||d.items[0].code!=='B01'||d.items[0].status!=='Done')throw Error('QA Lead Branch TV access failed: '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/tv/participants?type=AGENT',{auth:participantLogin}));if(r.status!==200||d.items.length!==1||d.items[0].code!=='A01')throw Error('Agent private TV scope failed: '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/tv/participants?type=BRANCH',{auth:participantLogin}));if(r.status!==403)throw Error('Agent gained Branch TV access');
 ({r,d}=await jsonRequest('/api/tv/participants?type=BRANCH',{auth:branchLogin}));if(r.status!==200||d.items.length!==1||d.items[0].code!=='B01')throw Error('Branch private TV scope failed: '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/tv/participants?type=AGENT',{auth:branchLogin}));if(r.status!==403)throw Error('Branch gained Agent TV access');
 ({r,d}=await jsonRequest('/api/tv/participants?type=AGENT',{auth:display}));if(r.status!==200)throw Error('Display cannot read Agent TV');
 const tech=await login('tech','Tech@123');({r,d}=await jsonRequest('/api/tv/participants?type=AGENT',{auth:tech}));if(r.status!==403)throw Error('Technical user gained participant TV access');
 const invalid=await workbookBuffer([[3,'Priority 1','WCX POS','Positive','Invalid participant',null,null,null,'Process',1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Expected',null,'Not Started',null,null,null,null,null,null,'WCX-003','A404']]);({r,d}=await jsonRequest('/api/test-cases/import-xlsx',{auth:admin,method:'POST',body:invalid,headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}}));if(r.status!==400||!d.errors?.some(x=>x.row===5&&x.field==='Participant Code'))throw Error('Row validation failed: '+JSON.stringify(d));({r,d}=await jsonRequest('/api/dashboard',{auth:manager}));if(d.total!==2)throw Error('Invalid workbook was partially imported');
 const missingFormula=await workbookBuffer([[4,'Priority 1','WCX POS','Positive','Missing formula result','PSP','04485572','KHR','Process',{formula:'1+1'},null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Expected',null,'Not Started',null,null,null,null,null,null,'WCX-004','A01']]);({r,d}=await jsonRequest('/api/test-cases/import-xlsx',{auth:admin,method:'POST',body:missingFormula,headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}}));if(r.status!==400||!d.errors?.some(x=>x.message.includes('cached result')))throw Error('Missing formula result was accepted: '+JSON.stringify(d));
 const movedRow=realRows()[0];movedRow[34]='A02';const movedWorkbook=await workbookBuffer([movedRow]);({r,d}=await jsonRequest('/api/test-cases/import-xlsx',{auth:admin,method:'POST',body:movedWorkbook,headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}}));if(r.status!==200||d.assignmentsCreated!==1||d.assignmentsUpdated!==0)throw Error('Repeat import created a second agent assignment: '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/test-cases',{auth:admin}));const importedMultiCase=d.items.find(x=>x.case_code==='WCX-001');if(importedMultiCase.assigned_users.length!==2)throw Error('Import replaced existing user');db.prepare('DELETE FROM assignments WHERE test_case_id=? AND participant_id=1').run(importedMultiCase.id);({r,d}=await jsonRequest('/api/test-cases',{auth:admin}));const movedCase=d.items.find(x=>x.case_code==='WCX-001');if(!movedCase||movedCase.assignments!==1||movedCase.participant_code!=='A02')throw Error('Imported participant_id mapping failed: '+JSON.stringify(movedCase));
 ({r,d}=await jsonRequest('/api/test-cases/'+movedCase.id+'/assignment',{auth:admin,method:'PUT',body:{participantId:1}}));if(r.status!==200)throw Error('Completed case rejected additional user');const addedToCompleted=db.prepare('SELECT id FROM assignments WHERE test_case_id=? AND participant_id=1').get(movedCase.id);await jsonRequest('/api/assignments/'+addedToCompleted.id,{auth:admin,method:'DELETE'});
 const newRow=[5,'Priority 1','WCX POS','Positive','Ready for assignment','PSP','04485572','KHR','Process',1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Expected',null,'Not Started',null,null,null,null,null,null,'WCX-005','A01'],secondNewRow=[6,'Priority 2','WCX POS','Positive','Second ready assignment','PSP','04485573','KHR','Process',2,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Expected two',null,'Not Started',null,null,null,null,null,null,'WCX-006','A01'],qaFlowRow=[7,'Priority 3','WCX POS','Positive','Agent QA submission','PSP','04485574','KHR','Process',3,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Expected three',null,'Not Started',null,null,null,null,null,null,'WCX-007','A01'];const newWorkbook=await workbookBuffer([newRow,secondNewRow,qaFlowRow]);({r,d}=await jsonRequest('/api/test-cases/import-xlsx',{auth:admin,method:'POST',body:newWorkbook,headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}}));if(r.status!==200)throw Error('Reassignment fixture import failed');({r,d}=await jsonRequest('/api/test-cases?status=NOT_STARTED&limit=10&offset=0',{auth:admin}));if(r.status!==200||d.total!==3||d.items.length!==3)throw Error('Assignable-only case filtering failed: '+JSON.stringify(d));const bulkCaseIds=d.items.filter(item=>['WCX-005','WCX-006'].includes(item.case_code)).map(item=>item.id);({r,d}=await jsonRequest('/api/test-cases/assignments',{auth:admin,method:'PUT',body:{caseIds:bulkCaseIds,participantId:2}}));if(r.status!==200||d.updated!==2)throw Error('Bulk test-case assignment failed: '+JSON.stringify(d));({r,d}=await jsonRequest('/api/test-cases',{auth:admin}));if(d.items.filter(x=>['WCX-005','WCX-006'].includes(x.case_code)).some(x=>!x.assigned_users.some(user=>user.code==='A02')))throw Error('Bulk assignment did not add every selected case');for(const caseId of bulkCaseIds){const original=db.prepare('SELECT id FROM assignments WHERE test_case_id=? AND participant_id=1').get(caseId);await jsonRequest('/api/assignments/'+original.id,{auth:admin,method:'DELETE'})}({r,d}=await jsonRequest('/api/test-cases/assignments',{auth:admin,method:'PUT',body:{caseIds:[999999,bulkCaseIds[0]],participantId:3}}));if(r.status!==404)throw Error('Bulk assignment accepted missing case');({r,d}=await jsonRequest('/api/test-cases',{auth:admin}));if(d.items.find(x=>x.id===bulkCaseIds[0]).participant_code!=='A02')throw Error('Invalid bulk assignment was not rolled back');
 ({r,d}=await jsonRequest('/api/my-assignments',{auth:observer}));if(r.status!==200||!d.items.length||d.items.some(x=>x.code!=='A02'))throw Error('Observer assignment scope failed: '+JSON.stringify(d));const observerReturnId=d.items.find(x=>x.case_code==='WCX-006').id;const observerCase=d.items.find(x=>x.case_code==='WCX-005');if(!observerCase)throw Error('Observer execution fixture is missing');({r,d}=await jsonRequest('/api/assignments/'+observerCase.id+'/status',{auth:observer,method:'PUT',body:{status:'IN_PROGRESS'}}));if(r.status!==200)throw Error('Observer could not start linked assignment: '+JSON.stringify(d));({r,d}=await jsonRequest('/api/assignments/'+observerCase.id+'/status',{auth:observer,method:'PUT',body:{status:'PENDING_QA',reportedResult:'PASSED',submissionNote:'Observer submitted linked assignment'}}));if(r.status!==200)throw Error('Observer could not submit linked assignment: '+JSON.stringify(d));({r,d}=await jsonRequest('/api/assignments/'+observerReturnId+'/status',{auth:manager,method:'PUT',body:{status:'IN_PROGRESS'}}));if(r.status!==403)throw Error('Manager gained participant execution access');
 r=await fetch(base+'/actions/login',{method:'POST',redirect:'manual',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'username=observer-a02&password=o'});if(r.status!==303||r.headers.get('location')!=='/my-tests')throw Error('Observer login did not redirect to My Tests');
 ({r,d}=await jsonRequest('/api/my-assignments',{auth:agent}));const qaFlow=d.items.find(item=>item.case_code==='WCX-007');if(!qaFlow)throw Error('Agent QA flow fixture is missing');({r,d}=await jsonRequest('/api/assignments/'+qaFlow.id+'/status',{auth:agent,method:'PUT',body:{status:'IN_PROGRESS'}}));if(r.status!==200)throw Error('Agent could not start QA flow case');({r,d}=await jsonRequest('/api/tv/participants?type=AGENT',{auth:participantLogin}));if(d.items[0].status!=='Testing'||d.items[0].progressPercent!==0)throw Error('Active work did not produce Testing TV status: '+JSON.stringify(d));({r,d}=await jsonRequest('/api/assignments/'+qaFlow.id+'/status',{auth:agent,method:'PUT',body:{status:'PENDING_QA',reportedResult:'PASSED',submissionNote:'Agent verified the expected result'}}));if(r.status!==200)throw Error('Agent result submission failed: '+JSON.stringify(d));({r,d}=await jsonRequest('/api/tv/participants?type=AGENT',{auth:participantLogin}));if(d.items[0].status!=='Done'||d.items[0].progressPercent!==100)throw Error('Pending QA submission did not produce Done TV status: '+JSON.stringify(d));({r,d}=await jsonRequest('/api/dashboard',{auth:manager}));if(d.completed!==1||d.pending!==3)throw Error('Unverified agent result changed management completion: '+JSON.stringify(d));({r,d}=await jsonRequest('/api/qa-submissions',{auth:qa}));const agentSubmission=d.items.find(x=>x.id===qaFlow.id);if(r.status!==200||!agentSubmission||agentSubmission.reported_result!=='PASSED'||agentSubmission.submission_note!=='Agent verified the expected result')throw Error('QA pending verification queue failed: '+JSON.stringify(d));({r,d}=await jsonRequest('/api/assignments/'+qaFlow.id+'/qa-review',{auth:qa,method:'PUT',body:{decision:'RETURN'}}));if(r.status!==200||d.status!=='RETESTING')throw Error('QA return failed: '+JSON.stringify(d));({r,d}=await jsonRequest('/api/tv/participants?type=AGENT',{auth:participantLogin}));if(d.items[0].status!=='Testing'||d.items[0].progressPercent!==0)throw Error('QA return did not restore Testing TV status: '+JSON.stringify(d));
 r=await fetch(base+'/qa',{headers:{Cookie:observer.cookie}});let observerQaHtml=await r.text();if(r.status!==200||!observerQaHtml.includes('Pending verification')||!observerQaHtml.includes('name="decision" value="APPROVE"'))throw Error('Observer QA controls missing');({r,d}=await jsonRequest('/api/qa-submissions',{auth:observer}));if(r.status!==200||!d.items.some(x=>x.id===observerCase.id))throw Error('Observer cannot read QA submissions');({r,d}=await jsonRequest('/api/assignments/'+observerCase.id+'/qa-review',{auth:observer,method:'PUT',body:{decision:'APPROVE',qaRemark:'Observer self-approved'}}));if(r.status!==200||d.status!=='COMPLETED')throw Error('Observer self-approval failed: '+JSON.stringify(d));({r,d}=await jsonRequest('/api/assignments/'+observerCase.id+'/status',{auth:observer,method:'PUT',body:{status:'IN_PROGRESS'}}));if(r.status!==409)throw Error('Observer restarted a completed assignment');({r,d}=await jsonRequest('/api/assignments/'+qaFlow.id+'/status',{auth:observer,method:'PUT',body:{status:'PENDING_QA',reportedResult:'PASSED'}}));if(r.status!==403)throw Error('Observer executed another participant assignment');
 ({r,d}=await jsonRequest('/api/assignments/'+observerReturnId+'/status',{auth:observer,method:'PUT',body:{status:'IN_PROGRESS'}}));if(r.status!==200)throw Error('Observer return fixture could not start');({r,d}=await jsonRequest('/api/assignments/'+observerReturnId+'/status',{auth:observer,method:'PUT',body:{status:'PENDING_QA',reportedResult:'PASSED',submissionNote:'Observer return fixture'}}));if(r.status!==200)throw Error('Observer return fixture could not submit');r=await fetch(base+'/actions/assignments/'+observerReturnId+'/review',{method:'POST',redirect:'manual',headers:{Cookie:observer.cookie,'HX-Request':'true','Content-Type':'application/x-www-form-urlencoded'},body:'_csrf='+encodeURIComponent(observer.csrf)+'&decision=RETURN&qaRemark=Observer+return'});if(r.status!==204||r.headers.get('hx-redirect')!=='/qa')throw Error('Observer HTMX QA review failed');if(db.prepare('SELECT status FROM assignments WHERE id=?').get(observerReturnId).status!=='RETESTING')throw Error('Observer return did not set Retesting');
 db.prepare("INSERT OR IGNORE INTO defects(assignment_id,severity,status) VALUES(?,'HIGH','REPORTED')").run(observerCase.id);const observerDefect=db.prepare('SELECT d.id FROM defects d JOIN assignments a ON a.id=d.assignment_id WHERE a.participant_id=2 ORDER BY d.id LIMIT 1').get();if(!observerDefect)throw Error('Observer defect fixture is missing');({r,d}=await jsonRequest('/api/defects/'+observerDefect.id+'/status',{auth:observer,method:'PUT',body:{status:'INVESTIGATING',owner:'Observer A02'}}));if(r.status!==200)throw Error('Observer defect update failed: '+JSON.stringify(d));const savedDefect=db.prepare('SELECT status,owner,updated_by FROM defects WHERE id=?').get(observerDefect.id);if(savedDefect.status!=='INVESTIGATING'||savedDefect.owner!=='Observer A02'||savedDefect.updated_by!=='observer-a02')throw Error('Observer defect attribution failed');r=await fetch(base+'/actions/defects/'+observerDefect.id,{method:'POST',redirect:'manual',headers:{Cookie:observer.cookie,'Content-Type':'application/x-www-form-urlencoded'},body:'_csrf='+encodeURIComponent(observer.csrf)+'&status=REOPENED&owner=Observer+A02'});if(r.status!==303||r.headers.get('location')!=='/qa')throw Error('Observer no-JS defect action failed');r=await fetch(base+'/qa',{headers:{Cookie:observer.cookie}});const updatedQa=await r.text();if(!updatedQa.includes('<h2>Test Cases</h2>')||!updatedQa.includes('Saved status: <span class="status REOPENED">REOPENED</span>'))throw Error('QA listing heading or saved status missing');
 for(const forbiddenPath of ['/admin']){r=await fetch(base+forbiddenPath,{headers:{Cookie:observer.cookie},redirect:'manual'});if(r.status!==403)throw Error('Observer accessed forbidden page '+forbiddenPath)}({r,d}=await jsonRequest('/api/users',{auth:observer}));if(r.status!==403)throw Error('Observer accessed account management');
 const scan=await fetch(base+'/scan?token='+encodeURIComponent(signedQr(2))),scanCookie=scan.headers.get('set-cookie').split(';')[0];({r,d}=await jsonRequest('/api/me',{auth:{cookie:scanCookie,csrf:''}}));if(r.status!==200||d.user.participantId!==2)throw Error('QR did not create a participant-scoped session');({r,d}=await jsonRequest('/api/my-assignments',{auth:{cookie:scanCookie,csrf:d.user.csrf}}));if(r.status!==200||d.items.length!==3||d.items.some(item=>item.code!=='A02'))throw Error('QR did not open all assigned agent test cases: '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/users',{auth:display,method:'POST',body:{username:'nope',password:'Nope@1234567',role:'DISPLAY',displayName:'Nope'}}));if(r.status!==403)throw Error('Display account gained write access');
 for(const tv of ['management','agents','branches']){r=await fetch(base+'/tv/'+tv,{headers:{Cookie:observer.cookie}});const screenHtml=await r.text();if(r.status!==200||screenHtml.includes('Technical TV'))throw Error('Observer TV denied '+tv);if(tv==='management'&&(!screenHtml.includes('>Passed<')||screenHtml.includes('>Completed<')))throw Error('Management TV labels incorrect')}
 for(const report of ['/api/dashboard','/api/tv/participants?type=AGENT','/api/tv/participants?type=BRANCH']){const global=await jsonRequest(report,{auth:admin}),observed=await jsonRequest(report,{auth:observer});if(observed.r.status!==200||JSON.stringify({...global.d,lastUpdated:null,serverTime:null})!==JSON.stringify({...observed.d,lastUpdated:null,serverTime:null}))throw Error('Observer report is not global '+report)}
 for(const account of [admin,observer,manager,display,tech,qa,participantLogin,branchLogin]){for(const removed of ['/tv/technical','/api/tv/technical']){r=await fetch(base+removed,{headers:{Cookie:account.cookie}});if(r.status!==404)throw Error('Technical TV still accessible '+removed)}}
 const pages=[['/admin',admin],['/my-tests',participantLogin],['/qa',qa],['/tv/management',manager],['/tv/agents',participantLogin],['/tv/branches',branchLogin]];
 r=await fetch(base+'/login');let html=await r.text();if(r.status!==200||!html.includes('/vendor/htmx-2.0.10.min.js')||html.includes('src="/app.js"'))throw Error('HTMX login shell failed');
 for(const [p,auth] of pages){r=await fetch(base+p,{headers:{Cookie:auth.cookie}});html=await r.text();if(r.status!==200||!html.includes('/vendor/htmx-2.0.10.min.js')||html.includes('src="/app.js"'))throw Error(p+' HTMX page failed')}
 const observerPages=[['/my-tests',['Submit to QA','Cases are ordered by channel and priority.']],['/qa',['Pending verification','class="defect-actions"']]];for(const [observerPath,markers] of observerPages){r=await fetch(base+observerPath,{headers:{Cookie:observer.cookie}});html=await r.text();if(r.status!==200)throw Error('Observer HTMX page failed: '+observerPath);for(const marker of markers)if(!html.includes(marker))throw Error(observerPath+' Observer parity missing: '+marker)}
 const parity={
  '/login':['Sign in with your assigned internal account.','class="muted"'],
  '/tv/management':['launch-label','Assignment status by delivery channel','Finance pending','risk-row','text-green','aria-label="Agent and Branch reports"'],
  '/tv/agents':['All assigned agents','aria-label="Participant progress"','aria-label="TV totals"'],
  '/my-tests':['Cases are ordered by channel and priority.','placeholder="Add execution details for QA"','class="qa-submit"'],
  '/qa':['Agent and branch results remain pending until QA approval.','Pending verification','Tester:','Finance:'],
  '/admin':['class="form"','Participant code','A01 for an Agent or B01 for a Branch','Any non-empty name is accepted.','assignment-filters','bulk-assignment','case-select-hit','select-page','Assigned agent','Status / action']
 };
 for(const [p,markers] of Object.entries(parity)){const auth=p==='/login'?null:p==='/tv/management'?manager:p==='/tv/agents'?admin:p==='/my-tests'?participantLogin:p==='/qa'?qa:admin;r=await fetch(base+p,{headers:auth?{Cookie:auth.cookie}:{}});html=await r.text();for(const marker of markers)if(!html.includes(marker))throw Error(p+' HTMX parity missing: '+marker)}
 r=await fetch(base+'/tv/management',{headers:{Cookie:manager.cookie,'HX-Request':'true','HX-Target':'content'}});html=await r.text();if(r.status!==200||html.includes('<!doctype html>')||!html.includes('Channel QA / result overview'))throw Error('HTMX fragment boundary failed');
 r=await fetch(base+'/actions/login',{method:'POST',redirect:'manual',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'username=admin&password=Admin%40123'});if(r.status!==303||r.headers.get('location')!=='/admin'||!r.headers.get('set-cookie'))throw Error('No-JS login PRG failed');
 r=await fetch(base+'/actions/assignments/'+qaFlow.id+'/submit',{method:'POST',redirect:'manual',headers:{Cookie:participantLogin.cookie,'HX-Request':'true','Content-Type':'application/x-www-form-urlencoded'},body:'_csrf='+encodeURIComponent(participantLogin.csrf)+'&reportedResult=PASSED&submissionNote=HTMX+submission'});if(r.status!==204||r.headers.get('hx-redirect')!=='/my-tests')throw Error('HTMX assignment action failed: '+r.status);
 ({r,d}=await jsonRequest('/api/qa-submissions',{auth:qa}));if(!d.items.some(x=>x.id===qaFlow.id&&x.submission_note==='HTMX submission'))throw Error('HTMX action did not reuse assignment logic');
 r=await fetch(base+'/actions/assignments/'+qaFlow.id+'/review',{method:'POST',redirect:'manual',headers:{Cookie:qa.cookie,'Content-Type':'application/x-www-form-urlencoded'},body:'_csrf='+encodeURIComponent(qa.csrf)+'&decision=RETURN&qaRemark=Retry'});if(r.status!==303||r.headers.get('location')!=='/qa')throw Error('No-JS QA review PRG failed');
 r=await fetch(base+'/actions/participants',{method:'POST',headers:{Cookie:admin.cookie,'Content-Type':'application/x-www-form-urlencoded'},body:'_csrf=wrong&code=A99&name=Wrong&type=AGENT'});html=await r.text();if(r.status!==403||!html.includes('Invalid security token'))throw Error('Form CSRF rejection failed');
 const multipart=new FormData();multipart.set('_csrf',admin.csrf);multipart.set('workbook',new Blob([invalid],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'invalid.xlsx');r=await fetch(base+'/actions/import-xlsx',{method:'POST',headers:{Cookie:admin.cookie,'HX-Request':'true'},body:multipart});html=await r.text();if(r.status!==400||!html.includes('Unknown or inactive participant A404'))throw Error('HTMX multipart validation failed: '+r.status+' '+html);
 for(const asset of ['/vendor/htmx-2.0.10.min.js','/vendor/htmx-ext-sse-2.2.4.js','/vendor/htmx-ext-response-targets-2.0.4.js','/htmx-client.js']){r=await fetch(base+asset);if(r.status!==200)throw Error('Vendored HTMX asset missing: '+asset)}
 // Observer ownership lifecycle: links, isolation, pagination, unlink and immediate revocation.
 ({r,d}=await jsonRequest('/api/observer/testers',{auth:observer,method:'POST',body:{participantId:21,observerId:emptyObserver.user.id}}));if(r.status!==201)throw Error('Observer could not link Branch');
 ({r,d}=await jsonRequest('/api/observer/assignments',{auth:observer}));if(r.status!==200||!d.items.some(x=>x.code==='B01')||d.items.some(x=>!['A02','B01'].includes(x.code)))throw Error('Multi-tester overview scope failed');
 ({r,d}=await jsonRequest('/api/my-assignments?participantId=1',{auth:observer}));if(r.status!==403)throw Error('Observer bypassed tester filter');
 ({r,d}=await jsonRequest('/api/observer/testers/2',{auth:emptyObserver,method:'DELETE'}));if(r.status!==403)throw Error('Observer unlinked someone else tester');
 const claims=await Promise.all([jsonRequest('/api/observer/testers',{auth:observer,method:'POST',body:{participantId:3}}),jsonRequest('/api/observer/testers',{auth:emptyObserver,method:'POST',body:{participantId:3}})]);if(claims.map(x=>x.r.status).sort().join(',')!=='201,409')throw Error('Concurrent tester claim failed');
 ({r,d}=await jsonRequest('/api/observer/testers',{auth:observer,method:'POST',body:{participantId:'bad'}}));if(r.status!==400)throw Error('Invalid tester accepted');
 ({r,d}=await jsonRequest('/api/observer/testers',{auth:observer,method:'POST',body:{participantId:999999}}));if(r.status!==404)throw Error('Missing tester accepted');
 ({r,d}=await jsonRequest('/api/observer/testers',{method:'POST',body:{participantId:4},headers:{Cookie:observer.cookie,'X-CSRF-Token':'invalid'}}));if(r.status!==403)throw Error('Observer link missing CSRF');
 for(const auth of [admin,manager,display,participantLogin,branchLogin]){r=await fetch(base+'/observer',{headers:{Cookie:auth.cookie}});if(r.status!==403)throw Error('Non-Observer accessed tab');({r,d}=await jsonRequest('/api/observer/testers',{auth}));if(r.status!==403)throw Error('Non-Observer accessed tester API')}
 r=await fetch(base+'/observer',{headers:{Cookie:observer.cookie}});html=await r.text();if(r.status!==200||!html.includes('Linked testers')||!html.includes('hx-confirm=')||!html.includes('name="confirmed"')||!html.includes('href="/observer"'))throw Error('Observer page controls missing');
 r=await fetch(base+'/my-tests',{headers:{Cookie:participantLogin.cookie}});html=await r.text();if(html.includes('href="/observer"'))throw Error('Observer nav leaked');
 for(let i=0;i<55;i++){const tc=db.prepare("INSERT INTO test_cases(case_code,title,process,channel) VALUES(?,?,?,?)").run('OBS-PAGE-'+i,'Observer pagination '+i,'Test','Observer Only');db.prepare('INSERT INTO assignments(test_case_id,participant_id) VALUES(?,2)').run(tc.lastInsertRowid)}
 ({r,d}=await jsonRequest('/api/observer/assignments?participantId=2&channel=Observer%20Only&page=2',{auth:observer}));if(r.status!==200||d.total!==55||d.items.length!==5)throw Error('Observer pagination failed');
 ({r,d}=await jsonRequest('/api/qa-submissions',{auth:emptyObserver}));if(d.items.some(x=>['A02','B01'].includes(x.participant_code))||d.availableChannels.includes('Observer Only'))throw Error('QA channels leaked');
 ({r,d}=await jsonRequest('/api/defects/'+observerDefect.id+'/status',{auth:emptyObserver,method:'PUT',body:{status:'INVESTIGATING'}}));if(r.status!==403)throw Error('Foreign defect update permitted');
 ({r,d}=await jsonRequest('/api/assignments/'+observerCase.id+'/qa-review',{auth:emptyObserver,method:'PUT',body:{decision:'APPROVE'}}));if(r.status!==403)throw Error('Foreign QA review permitted');
 const beforeUnlink=db.prepare('SELECT * FROM assignments WHERE id=?').get(observerCase.id);
 r=await fetch(base+'/actions/observer/testers/2/unlink',{method:'POST',redirect:'manual',headers:{Cookie:observer.cookie,'Content-Type':'application/x-www-form-urlencoded'},body:'_csrf='+encodeURIComponent(observer.csrf)+'&confirmed=1'});if(r.status!==303||r.headers.get('location')!=='/observer')throw Error('No-JS unlink failed');
 if(JSON.stringify(beforeUnlink)!==JSON.stringify(db.prepare('SELECT * FROM assignments WHERE id=?').get(observerCase.id)))throw Error('Unlink changed assignment');
 ({r,d}=await jsonRequest('/api/assignments/'+observerCase.id+'/status',{auth:observer,method:'PUT',body:{status:'IN_PROGRESS'}}));if(r.status!==403)throw Error('Unlink did not revoke execution');
 ({r,d}=await jsonRequest('/api/assignments/'+observerCase.id+'/qa-review',{auth:observer,method:'PUT',body:{decision:'APPROVE'}}));if(r.status!==403)throw Error('Unlink did not revoke QA');
 ({r,d}=await jsonRequest('/api/defects/'+observerDefect.id+'/status',{auth:observer,method:'PUT',body:{status:'INVESTIGATING'}}));if(r.status!==403)throw Error('Unlink did not revoke defects');
 ({r,d}=await jsonRequest('/api/observer/testers',{auth:emptyObserver}));if(!d.available.some(x=>x.id===2))throw Error('Unlinked tester unavailable');
 r=await fetch(base+'/actions/observer/link',{method:'POST',redirect:'manual',headers:{Cookie:emptyObserver.cookie,'HX-Request':'true','Content-Type':'application/x-www-form-urlencoded'},body:'_csrf='+encodeURIComponent(emptyObserver.csrf)+'&participantId=2'});if(r.status!==204||r.headers.get('hx-redirect')!=='/observer')throw Error('HTMX link failed');
 if(!db.prepare("SELECT id FROM audit_log WHERE action='UNLINK' AND entity_type='OBSERVER_TESTER' AND entity_id=2").get())throw Error('Unlink audit missing');
 const serverSource=fs.readFileSync(path.join(__dirname,'server.js'),'utf8');for(const marker of ["CREATE TABLE IF NOT EXISTS observer_participants","DROP INDEX IF EXISTS idx_users_observer_login","FRONTEND_MODE!=='htmx'&&routes[url.pathname]"])if(!serverSource.includes(marker))throw Error('Observer hardening missing: '+marker);
 const viewSource=fs.readFileSync(path.join(__dirname,'lib','htmx-views.js'),'utf8')+fs.readFileSync(path.join(__dirname,'public','case-ui.js'),'utf8'),clientSource=fs.readFileSync(path.join(__dirname,'public','htmx-client.js'),'utf8');for(const marker of ['/actions/users/','/actions/test-cases/','Channel import summary','Manager and display accounts','data-countdown','source_details','Previous','Next','class="assignment-table"','class="assignment-priority"','class="assignment-agent"','class="assignment-status"','class="defect-actions"','<option value="OBSERVER">Observer</option>',"['ADMIN','QA_LEAD','OBSERVER']","['ADMIN','QA_LEAD','TECH','OBSERVER']"])if(!viewSource.includes(marker))throw Error('Missing HTMX parity behavior: '+marker);if(viewSource.includes('change from:select'))throw Error('HTMX filter listens to unrelated dropdowns');if((viewSource.match(/hx-trigger="change"/g)||[]).length<2)throw Error('HTMX filters are not scoped to their own selects');if(!clientSource.includes('data-countdown'))throw Error('HTMX countdown adapter missing');for(const marker of ['function syncPageMode(url)','event.detail.xhr?.responseURL','document.body.className=tvPath?\'tv tv-\'+section:\'\'','syncPageMode(event.detail.xhr?.responseURL||location.href)'])if(!clientSource.includes(marker))throw Error('HTMX page-mode synchronization missing: '+marker);
 const appSource=fs.readFileSync(path.join(__dirname,'public','app.js'),'utf8');
 const appMarkers=['observer-tester-identity','channel-filter','Channel QA / result overview','import-production','finance_status','reported-result','submission-note','Pending verification','Submitted cases','Testing participants','Done participants','/api/tv/participants?type=','tv-tabs','Management TV','Agent TV','Branch TV','Agent Report','Branch Report','management-participant-reports','managementParticipantReport','Promise.all([api(\'/api/dashboard\'),api(\'/api/tv/participants?type=AGENT\'),api(\'/api/tv/participants?type=BRANCH\')])','No assigned Agent data','No assigned Branch data','function roleHomePath()','function backAction()','function logoutAction()','tv?backAction():homeAction()','liveStatus()+\'</span>\'+logoutAction()','INTERNAL WORKSPACE</span>\'+logoutAction()','me?.role===\'ADMIN\'?\'/admin\'','data-action="home"','class="header-action back-icon alt"','data-action="back" aria-label="Go back" title="Go back">←</button>','data-action="logout"','/api/logout','history.back()','me?.role===\'OBSERVER\'?\'/my-tests\'','<option value="OBSERVER">Observer</option>'];
 const responsiveAppMarkers=['class="menu-toggle"','aria-expanded="false"','aria-controls="workspace-navigation"','id="workspace-navigation"','setupResponsiveNavigation','document.body.classList.add(\'nav-enhanced\')','button.setAttribute(\'aria-expanded\',String(expanded))','class="table-scroll-hint"','<div class="table-scroll" role="region" tabindex="0" aria-label="Channel import summary table">','<div class="table-scroll" role="region" tabindex="0" aria-label="Test case assignments table">','<label class="case-select-hit"><input class="case-select"','<label class="case-select-hit"><input id="select-page"'];
 for(const marker of [...appMarkers,...responsiveAppMarkers])if(!appSource.includes(marker))throw Error('Missing UI behavior: '+marker);if(/\bonclick\s*=|\bstyle\s*=/.test(appSource))throw Error('Inline handler/style conflicts with CSP');
 if(!appSource.includes('source_case_id')||!appSource.includes('productionBadge')||!appSource.includes('displayCaseId'))throw Error('Production case ID and status display are missing');
 if(!appSource.includes('<section class="card full channel-summary"><h2>Channel import summary</h2>'))throw Error('Channel import summary must span the full Administration grid');
 if(!appSource.includes('A01 for an Agent or B01 for a Branch'))throw Error('Participant code guidance is missing');
 if(appSource.includes('class="card full participants-qr"'))throw Error('Retired QR section remains');
 if(!appSource.includes("const gridClass=type==='AGENT'?'agent-grid':'branch-grid';"))throw Error('Participant TV does not select a route-specific grid class');
 if(!appSource.includes("class=\"participant-tv-list'+(privateView?' private-view':' '+gridClass)+'\""))throw Error('Participant TV grid class is not connected to public runtime markup or private-view isolation');
 const styleSource=fs.readFileSync(path.join(__dirname,'public','style.css'),'utf8');
 const styleMarkers=['.channel-overview','.channel-badge','.detail-grid','.channel-badge { white-space: nowrap','.header-action','.back-icon','.management-participant-reports','.management-report-list','.assignment-table .assignment-priority','.assignment-table .assignment-agent','.assignment-table .assignment-status','.defect-actions { display: grid;','.defect-actions > * { width: 100%;','.assignment-table .assignment-agent form { display: grid;','.assignment-table .assignment-agent button { width: 100%;','@media (max-width: 1280px)','.assignment-filters select, .bulk-assignment select { margin: 0; }'];
 const responsiveStyleMarkers=['.menu-toggle','body.nav-enhanced:not(.tv)','aria-expanded="true"','@media (max-width: 767px)','@media (min-width: 768px)','@media (min-width: 768px) and (max-width: 1023px)','@media (min-width: 2560px)','@media (prefers-reduced-motion: reduce)','scroll-behavior: auto','body:not(.tv)','.tv-management','.tv-technical','.tv-agents','.tv-branches','overscroll-behavior-inline: contain','body:not(.tv) .table-scroll { max-width: 100%; overflow-x: auto; overscroll-behavior-inline: contain; scrollbar-gutter: stable; }','body:not(.tv) .table-scroll:focus-visible { outline: 3px solid var(--focus); outline-offset: -3px; }','.tv .table-scroll { max-width: 100%; overflow-x: auto; }','body:not(.tv) .table-scroll table { min-width: 48rem; }','.case-select-hit { display: grid; place-items: center; width: 44px; height: 44px; cursor: pointer; }','body:not(.tv) .assignment-filters, body:not(.tv) .bulk-assignment { display: grid; grid-template-columns: 1fr; align-items: stretch; width: 100%; }','body:not(.tv) .pagination { flex-wrap: wrap; }','body:not(.tv) .case-row, body:not(.tv) .qa-review-row, body:not(.tv) .defect-row { grid-template-columns: 1fr; }','body:not(.tv) .qa-review-row { grid-template-columns: minmax(0, 1fr) 12rem; }','body:not(.tv) .defect-row { grid-template-columns: minmax(0, 1fr) minmax(14rem, 18rem); }'];
 for(const marker of [...styleMarkers,...responsiveStyleMarkers])if(!styleSource.includes(marker))throw Error('Missing responsive layout: '+marker);
 requireCss(styleSource,['.tv .shell { max-width: none; min-height: 100vh; height: 100vh;','.tv-agents .agent-grid, .tv-branches .branch-grid { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr));','.tv-agents .participant-tv-list.agent-grid, .tv-branches .participant-tv-list.branch-grid { grid-template-columns: repeat(2, minmax(20em, 1fr)); grid-template-rows: none; }','.tv-agents .agent-grid { grid-template-rows: repeat(4, minmax(9em, 1fr)); }','.tv-branches .branch-grid { grid-template-rows: repeat(2, minmax(9em, 1fr)); }','.tv-management .management-grid { grid-template-columns: minmax(0, 3fr) minmax(13em, 1fr); flex: 1; min-height: 0; }','.tv-management .management-people .people { flex: 1; grid-auto-rows: 1fr; overflow-y: auto; }','.tv-technical .technical-list { min-height: 0; overflow-y: auto; }'],'TV fixed-screen relationship');
 const fourK=cssBlock(styleSource,'@media (min-width: 2560px)'),widthFallback=cssBlock(styleSource,'@media (max-width: 1100px)'),heightFallback=cssBlock(styleSource,'@media (max-height: 820px)'),tabletTv=cssBlock(styleSource,'@media (max-width: 800px)'),phoneTv=cssBlock(styleSource,'@media (max-width: 480px)');
 requireCss(fourK,['.tv { font-size: clamp(1.5rem, 1.042vw, 2.5rem); }','.tv .shell { padding: clamp(1.5rem, 1vw, 2.5rem); }','.tv .site-header { border-top-width: clamp(5px, 0.25vw, 10px); }'],'4K TV relationship');
 requireCss(widthFallback,['.tv .shell { height: auto; min-height: 100vh; }','.tv-management .management-grid { flex: auto; }','.tv-agents .agent-grid, .tv-branches .branch-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); grid-template-rows: none; grid-auto-rows: minmax(190px, auto); }','.tv .tile { overflow: visible; }'],'TV width fallback relationship');
 requireCss(heightFallback,['.tv .shell { height: auto; min-height: 100vh; }','.tv-management .management-grid { flex: auto; }','.tv-management .management-people .people, .tv-technical .technical-list { overflow-y: visible; }'],'TV height fallback relationship');
 requireCss(tabletTv,['.tv .shell { padding: 0.75rem; }','.tv .brand-logo { width: 110px; height: 37px; }','.tv-management .management-grid { grid-template-columns: 1fr; }','.tv .people, .tv-agents .agent-grid, .tv-branches .branch-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }','.tv .row { grid-template-columns: 1fr 1fr; }','.tv .case-row, .tv .defect-row, .tv .participant-tv-list { grid-template-columns: 1fr; }','.tv .detail-grid, .tv .metrics { grid-template-columns: repeat(2, minmax(0, 1fr)); }','.tv .countdown { flex-wrap: wrap; }','.tv-technical .technical-list { overflow-y: visible; }'],'800px TV fallback relationship');
 requireCss(tabletTv,['.management-participant-reports { grid-template-columns: 1fr; }'],'Management report mobile stacking');
 requireCss(phoneTv,['.tv .brand-divider { display: none; }','.tv .brand-identity { flex-wrap: wrap; }','.tv .brand-copy { width: 100%; }','.tv .live { margin-left: 0; }','.tv .people, .tv-agents .agent-grid, .tv-branches .branch-grid, .tv .row, .tv .detail-grid { grid-template-columns: 1fr; }','.tv .qa-summary .row { grid-template-columns: 1fr auto; }','.tv .countdown > div { min-width: 3.3rem; }','body:not(.tv) .login { padding: 1.5rem; }'],'480px isolated fallback relationship');
 if(/@media\s*\(max-width:\s*1100px\)\s*,\s*\(max-height:\s*820px\)/.test(styleSource))throw Error('TV width and height fallbacks must use independent media queries');
 db.prepare("INSERT INTO users(username,password_hash,role,display_name) VALUES('unlinked-agent-test',?,'AGENT','Unlinked Agent')").run(db.prepare("SELECT password_hash FROM users WHERE username='agent01'").get().password_hash);const unlinkedAgent=await login('unlinked-agent-test','Agent@123');({r,d}=await jsonRequest('/api/assignments/'+qaFlow.id+'/status',{auth:unlinkedAgent,method:'PUT',body:{status:'PENDING_QA',reportedResult:'PASSED'}}));if(r.status!==403)throw Error('Unlinked Agent gained participant execution access');
 const conflictDbPath=path.join(testDirectory,'observer-index-conflict.db'),conflictDb=new DatabaseSync(conflictDbPath);conflictDb.exec("CREATE TABLE users(id INTEGER PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL,display_name TEXT NOT NULL,active INTEGER DEFAULT 1,participant_id INTEGER);INSERT INTO users(username,password_hash,role,display_name,participant_id) VALUES('observer-conflict-1','hash','OBSERVER','Observer One',99),('observer-conflict-2','hash','OBSERVER','Observer Two',99)");conflictDb.close();const conflictStartup=spawnSync(process.execPath,['-e',"require('./server')"],{cwd:__dirname,env:{...process.env,DB_FILE:conflictDbPath,PORT:'18081',HOST:'127.0.0.1',SEED_DEMO_DATA:'false'},encoding:'utf8',timeout:10000});if(conflictStartup.status===0||!conflictStartup.stderr.includes('Cannot enforce one Observer login for participant_id 99'))throw Error('Observer migration conflict was not actionable: '+conflictStartup.stderr);
 const migrationPath=path.join(testDirectory,'observer-migrate.db'),migrationDb=new DatabaseSync(migrationPath);
 migrationDb.exec("CREATE TABLE participants(id INTEGER PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL,active INTEGER DEFAULT 1,observer TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);INSERT INTO participants(id,code,name,type) VALUES(99,'A99','Migration tester','AGENT');CREATE TABLE users(id INTEGER PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL,display_name TEXT NOT NULL,active INTEGER DEFAULT 1,participant_id INTEGER);INSERT INTO users(id,username,password_hash,role,display_name,participant_id) VALUES(99,'legacy-observer','hash','OBSERVER','Legacy Observer',99)");migrationDb.close();
 const migrationRun=code=>spawnSync(process.execPath,['-e',code],{cwd:__dirname,env:{...process.env,DB_FILE:migrationPath,PORT:'18082'},encoding:'utf8',timeout:10000});
 let migrated=migrationRun("const {server,db}=require('./server');server.once('listening',()=>{if(db.prepare('SELECT observer_user_id FROM observer_participants WHERE participant_id=99').get()?.observer_user_id!==99||db.prepare('SELECT participant_id FROM users WHERE id=99').get().participant_id!==null)process.exitCode=1;db.prepare('DELETE FROM observer_participants WHERE participant_id=99').run();server.close(()=>db.close())})");if(migrated.status!==0)throw Error('Observer legacy migration failed: '+migrated.stderr);
 migrated=migrationRun("const {server,db}=require('./server');server.once('listening',()=>{if(db.prepare('SELECT 1 FROM observer_participants WHERE participant_id=99').get())process.exitCode=1;server.close(()=>db.close())})");if(migrated.status!==0)throw Error('Observer unlink restored on restart: '+migrated.stderr);
 const sample=fs.readFileSync('/Users/sam/Downloads/1.1 Channel- WCX POS.xlsx');
 const beforeChannel=db.prepare('SELECT COUNT(*) c FROM test_cases').get().c;
 ({r,d}=await jsonRequest('/api/test-cases/import-production?channel=Custom%20POS',{auth:admin,method:'POST',headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'},body:sample}));if(r.status!==200||d.insertedCases!==530||d.channel!=='Custom POS')throw Error('Named production import failed: '+JSON.stringify(d));
 ({r,d}=await jsonRequest('/api/test-cases/import-production?channel=custom%20pos',{auth:admin,method:'POST',body:sample}));if(r.status!==200||d.insertedCases!==0||d.updatedCases!==530||db.prepare('SELECT COUNT(*) c FROM test_cases').get().c!==beforeChannel+530)throw Error('Production channel reimport duplicated or removed cases');
 ({r,d}=await jsonRequest('/api/test-cases/import-production',{auth:admin,method:'POST',body:sample}));if(r.status!==400)throw Error('Channel name required');
 const sheetFixture=db.prepare('SELECT source_sheet,priority FROM test_cases WHERE channel=? LIMIT 1').get('Custom POS');
 const filterQuery=new URLSearchParams({channel:'Custom POS',sheet:sheetFixture.source_sheet,priority:String(sheetFixture.priority)});
 ({r,d}=await jsonRequest('/api/test-cases?'+filterQuery,{auth:admin}));if(r.status!==200||!d.items.length||d.items.some(x=>x.source_sheet!==sheetFixture.source_sheet||x.priority!==sheetFixture.priority)||!d.availableSheets.includes(sheetFixture.source_sheet))throw Error('Sheet/priority filters failed');
 ({r,d}=await jsonRequest('/api/test-cases?priority=invalid',{auth:admin}));if(r.status!==400)throw Error('Invalid priority accepted');
 r=await fetch(base+'/admin?'+filterQuery,{headers:{Cookie:admin.cookie}});const filteredHtml=await r.text();if(!filteredHtml.includes('name="sheet"')||!filteredHtml.includes('name="priority"'))throw Error('Assignment filter controls missing');
 const confirmationCase=db.prepare("INSERT INTO test_cases(case_code,title,process) VALUES('CONFIRM-CASE','Confirmation fixture','Fixture')").run().lastInsertRowid;
 db.prepare('INSERT INTO assignments(test_case_id,participant_id,status) VALUES(?,?,?)').run(confirmationCase,1,'NOT_STARTED');
 const confirmationBody=new URLSearchParams({_csrf:admin.csrf,participantId:'3'});
 r=await fetch(base+'/actions/test-cases/'+confirmationCase+'/assignment',{method:'POST',redirect:'manual',headers:{Cookie:admin.cookie,'Content-Type':'application/x-www-form-urlencoded'},body:confirmationBody});if(r.status!==303||db.prepare('SELECT COUNT(*) n FROM assignments WHERE test_case_id=? AND participant_id IN (1,3)').get(confirmationCase).n!==2)throw Error('Ordinary additive assignment failed');

 const originalUsers=db.prepare('SELECT COUNT(*) c FROM users').get().c,backupDirectory=path.join(testDirectory,'backups'),backup=await backupDatabase(process.env.DB_FILE,backupDirectory),replacement=replaceProductionData(db,[...pos.records,...ekyc.records],'admin',[{fileName:'pos.xlsx',excludedSheets:pos.excludedSheets},{fileName:'ekyc.xlsx',excludedSheets:ekyc.excludedSheets}]);if(replacement.total!==800||replacement.channels['WCX POS']!==530||replacement.channels['WCX eKYC']!==270||db.prepare('SELECT COUNT(*) c FROM test_cases').get().c!==800||db.prepare('SELECT COUNT(*) c FROM assignments WHERE participant_id IS NULL AND workflow_state=\'UNASSIGNED\'').get().c!==800||db.prepare('SELECT COUNT(*) c FROM users').get().c!==originalUsers)throw Error('Production replacement reconciliation failed');if(!fs.existsSync(backup)||new DatabaseSync(backup).prepare('SELECT COUNT(*) c FROM test_cases').get().c<1)throw Error('Production backup is invalid');
 const {resetLocalDatabase}=require('./lib/fresh-start');
 const adminBefore=db.prepare("SELECT * FROM users WHERE role='ADMIN' ORDER BY id").all();
 const reset=resetLocalDatabase(process.env.DB_FILE),backupDb=new DatabaseSync(reset.backup,{readOnly:true});
 if(backupDb.prepare('PRAGMA integrity_check').get().integrity_check!=='ok'||backupDb.prepare('SELECT COUNT(*) n FROM test_cases').get().n!==800||backupDb.prepare('SELECT COUNT(*) n FROM users').get().n!==originalUsers)throw Error('Reset backup lost original data');backupDb.close();
 if(JSON.stringify(db.prepare("SELECT * FROM users WHERE role='ADMIN' ORDER BY id").all())!==JSON.stringify(adminBefore)||reset.after.users!==adminBefore.length||reset.after.audit_log!==1||['test_cases','assignments','defects','participants','observer_participants'].some(t=>reset.after[t]))throw Error('Reset failed preservation or clearing');
 const freshAdmin=await login('admin','Admin@123');({r,d}=await jsonRequest('/api/me',{auth:freshAdmin}));if(r.status!==200)throw Error('First login after reset revoked');
 ({r,d}=await jsonRequest('/api/me',{auth:qa}));if(r.status!==401)throw Error('Reset retained deleted user session');({r,d}=await jsonRequest('/api/me',{auth:{cookie:scanCookie,csrf:''}}));if(r.status!==401)throw Error('Reset retained QR session');
 await login('admin','Admin@123');
 const restarted=spawnSync(process.execPath,['-e',"const {db}=require('./server');if(db.prepare('SELECT COUNT(*) n FROM users').get().n!==1||db.prepare('SELECT COUNT(*) n FROM participants').get().n||db.prepare('SELECT COUNT(*) n FROM test_cases').get().n)process.exitCode=1;db.close()"],{cwd:__dirname,env:{...process.env,SERVERLESS:'true',SEED_DEMO_DATA:'true'},encoding:'utf8'});if(restarted.status!==0)throw Error('Restart recreated samples: '+restarted.stderr);
 console.log('PASS: channel-aware XLSX import, atomic validation, dashboard aggregation, role access, Observer ownership lifecycle/migration, filtered APIs and branded UI smoke checks.');
}
function cleanup(){server.close();db.close();fs.rmSync(testDirectory,{recursive:true,force:true})}
server.once('listening',()=>run().catch(error=>{console.error(error);process.exitCode=1}).finally(cleanup));
