'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ptc-rounds-'));
Object.assign(process.env,{SERVERLESS:'true',NODE_ENV:'test',DB_FILE:path.join(dir,'test.db'),DEMO_MODE:'false'});
const {server,db}=require('../server');
let base,cookie,csrf;
async function request(url,method='GET',body,token=csrf){const response=await fetch(base+url,{method,headers:{Cookie:cookie||'','Content-Type':'application/json','X-CSRF-Token':token||''},body:body?JSON.stringify(body):undefined});return {status:response.status,data:await response.json()}}
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;
 const login=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'admin',password:'Admin@123'})});cookie=login.headers.get('set-cookie').split(';')[0];csrf=(await login.json()).user.csrf;
 assert.equal((await request('/api/my-agent')).status,200,'My Agent overview must exist');
 for(let i=1;i<=7;i++)db.prepare('INSERT INTO participants(code,name,type) VALUES(?,?,?)').run('A0'+i,'Agent '+i,'AGENT');
 db.exec("INSERT INTO participants(code,name,type) VALUES('B01','Branch','BRANCH')");
 assert.equal((await request('/api/my-agent/loop')).data.step,1);
 assert.equal((await request('/api/my-agent/loop/next-step','POST',{round:1,step:1},'wrong')).status,403);
 assert.equal((await request('/api/my-agent/loop/next','POST',{round:1,step:1})).status,409);
 assert.equal((await request('/api/my-agent/loop/next-step','POST',{round:1,step:1})).status,200);
 assert.equal((await request('/api/my-agent/loop/next-step','POST',{round:1,step:1})).status,409);
 assert.deepEqual((await request('/api/my-agent/loop')).data.items.map(i=>i.features.length),[0,1,1,0,0,0,0]);
 for(let step=2;step<7;step++)assert.equal((await request('/api/my-agent/loop/next-step','POST',{round:1,step})).status,200);
 assert.equal((await request('/api/my-agent/loop/next','POST',{round:1,step:7})).status,200);
 const changed=(await request('/api/my-agent/loop')).data;assert.equal(changed.round,2);assert.equal(changed.step,1);assert.equal(changed.roundValues.amount,'25.01 USD / 100,100 KHR');
 assert.equal((await request('/api/my-agent/scenarios','POST',{name:'Bad',amount:-1,currency:'KHR',subtasks:[]})).status,400);
 assert.equal((await request('/api/my-agent/scenarios','POST',{name:'Test',amount:1,currency:'USD',subtasks:[{name:'Step',expectedResult:'Pass'}]},'wrong')).status,403);
 for(let i=1;i<=9;i++)assert.equal((await request('/api/my-agent/scenarios','POST',{name:'Scenario '+i,amount:100,currency:'KHR',subtasks:[{name:'First',expectedResult:'Expected 1'},{name:'Second',expectedResult:'Expected 2'}]})).status,201);
 let overview=(await request('/api/my-agent')).data;assert.equal(overview.agents.length,7);assert.equal(overview.queue.length,9);
 let preview=(await request('/api/my-agent/next','POST',{})).data.preview;
 assert.equal(preview.items.length,7);assert.deepEqual(preview.items.map(x=>x.code),['A01','A02','A03','A04','A05','A06','A07']);
 assert.equal(db.prepare('SELECT COUNT(*) n FROM assignments').get().n,0,'preview must not assign');
 assert.equal((await request('/api/my-agent/assign','POST',{token:preview.token})).status,200);
 assert.equal(db.prepare('SELECT COUNT(*) n FROM assignments').get().n,14);
 assert.equal((await request('/api/my-agent/assign','POST',{token:preview.token})).status,409,'repeat click must not duplicate');
 const first=db.prepare('SELECT id FROM assignments ORDER BY id LIMIT 1').get().id;
 db.prepare("UPDATE assignments SET status='IN_PROGRESS',actual_result='Keep result' WHERE id=?").run(first);
 preview=(await request('/api/my-agent/next','POST',{})).data.preview;
 assert.equal(db.prepare('SELECT state FROM agent_rounds WHERE number=1').get().state,'DONE','Admin Next closes round without QA');
 assert.equal(db.prepare('SELECT actual_result FROM assignments WHERE id=?').get(first).actual_result,'Keep result');
 assert.deepEqual(preview.items.map(x=>x.code),['A01','A02']);
 db.exec("UPDATE participants SET active=0 WHERE code='A01'");
 assert.equal((await request('/api/my-agent/assign','POST',{token:preview.token})).status,409,'inactive agent invalidates preview');
 preview=(await request('/api/my-agent/next','POST',{})).data.preview;
 assert.deepEqual(preview.items.map(x=>x.code),['A02','A03']);
 assert.equal((await request('/api/my-agent/assign','POST',{token:preview.token})).status,200);
 overview=(await request('/api/my-agent')).data;assert.equal(overview.round.number,2);assert.equal(overview.queue.length,0);
 assert.equal(db.prepare('SELECT COUNT(DISTINCT a.participant_id) n FROM assignments a JOIN agent_scenario_cases sc ON sc.case_id=a.test_case_id GROUP BY sc.scenario_id LIMIT 1').get().n,1,'scenario subtasks share agent');
 const removable=db.prepare('SELECT id,test_case_id FROM assignments ORDER BY id DESC LIMIT 1').get();
 assert.equal((await request('/api/assignments/'+removable.id,'DELETE')).status,409,'round subtasks cannot be individually removed');
 assert.equal((await request('/api/test-cases/'+removable.test_case_id+'/assignment','PUT',{participantId:7})).status,409,'round scenario owner must stay intact');
 const ExcelJS=require('exceljs'),workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('Cases');
 sheet.addRow(['Case ID','Participant Code','Channel','Scenario','Priority Level','Expected Result','Status']);
 sheet.addRow(['MA-1-1','A07','Cash','Overwrite',3,'Wrong','Passed']);
 const upload=await fetch(base+'/api/test-cases/import-xlsx',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','X-CSRF-Token':csrf},body:await workbook.xlsx.writeBuffer()});
 assert.equal(upload.status,409,'workbook cannot overwrite round subtasks');
 const last=db.prepare('SELECT last_agent_id FROM agent_round_state WHERE id=1').get().last_agent_id;
 db.prepare('UPDATE participants SET active=0 WHERE id=?').run(last);
 await request('/api/my-agent/scenarios','POST',{name:'Successor',amount:1,currency:'USD',subtasks:[{name:'Step',expectedResult:'Pass'}]});
 const successor=(await request('/api/my-agent/next','POST',{})).data.preview;
 assert.equal(successor.items[0].code,'A04','paused cursor must continue to successor');
 await request('/api/my-agent/cancel','POST',{});
 const page=await (await fetch(base+'/my-agent',{headers:{Cookie:cookie}})).text();assert.match(page,/My Agent/);assert.match(page,/src="\/my-agent.js\?v=[a-f0-9]+"/);
 const client=await (await fetch(base+'/my-agent.js')).text();assert.doesNotMatch(client,/Add Scenario/);assert.match(client,/Next Round/);
 const adminPage=await (await fetch(base+'/admin',{headers:{Cookie:cookie}})).text();assert.match(adminPage,/href="\/my-agent"/);assert.doesNotMatch(adminPage,/>Remove<|>Add user</,'Administration must not offer forbidden subtask edits');
 await request('/api/users','POST',{username:'agent1',displayName:'Agent 1',role:'AGENT',participantId:2,password:'test'});
 const agentLogin=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'agent1',password:'test'})});cookie=agentLogin.headers.get('set-cookie').split(';')[0];csrf=(await agentLogin.json()).user.csrf;
 assert.equal((await request('/api/my-agent/loop')).status,403);
 assert.equal((await request('/api/my-agent')).status,403);assert.equal((await fetch(base+'/my-agent',{headers:{Cookie:cookie}})).status,403);
 const tests=await (await fetch(base+'/my-tests',{headers:{Cookie:cookie}})).text();assert.match(tests,/Scenario 2/);assert.match(tests,/Expected 1/);
 const assigned=(await request('/api/my-assignments')).data.items;
 assert.deepEqual(assigned.map(x=>x.title),['Scenario 2 · First','Scenario 2 · Second','Scenario 8 · First','Scenario 8 · Second'],'steps stay grouped across rounds');
 const records=Array.from({length:800},(_,i)=>({durableKey:'replacement-'+i,sourceCaseId:'R-'+i,channel:i<530?'WCX POS':'WCX eKYC',subcategory:'Standard',scenario:'Imported '+i,priority:3,steps:'Step',expectedResult:'Pass',caseType:'Positive',sourceSheet:'Standard',row:i+1,productionStatus:'PENDING',actualResult:'',qaTester:'',executedAt:null,qaRemark:'',jiraLink:'',financeStatus:'',financeRemark:'',details:{}}));
 require('../lib/production-replacement').replaceProductionData(db,records,'admin');
 assert.equal(db.prepare('SELECT COUNT(*) n FROM agent_scenario_cases').get().n,18,'production replacement preserves My Agent steps');
 assert.equal(db.prepare('SELECT actual_result FROM assignments WHERE id=?').get(first).actual_result,'Keep result');
 require('../lib/fresh-start').resetLocalDatabase(process.env.DB_FILE);
 assert.equal(db.prepare('SELECT COUNT(*) n FROM agent_scenarios').get().n,0,'fresh reset clears scenario history');
 console.log('PASS: My Agent creation, validation, seven-agent rounds, previews, stale/repeated requests, preserved results, Admin access, agent test integration');
})().catch(error=>{console.error(error);process.exitCode=1}).finally(async()=>{await new Promise(resolve=>server.close(resolve));db.close();fs.rmSync(dir,{recursive:true,force:true})});
