'use strict';
const schedule=require('../public/agent-loop-schedule.json');
const fail=(message)=>{throw Object.assign(Error(message),{status:409})};
function setup(db){db.exec(`CREATE TABLE IF NOT EXISTS agent_loop_state(id INTEGER PRIMARY KEY CHECK(id=1),round INTEGER NOT NULL DEFAULT 0);INSERT OR IGNORE INTO agent_loop_state(id,round) VALUES(1,1);UPDATE agent_loop_state SET round=1 WHERE round=0;CREATE TABLE IF NOT EXISTS agent_loop_results(round INTEGER NOT NULL,tester INTEGER NOT NULL,participant_id INTEGER NOT NULL,completed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_by TEXT NOT NULL,PRIMARY KEY(round,tester));`)}
function people(db){return Array.from({length:7},(_,i)=>db.prepare("SELECT id,code,name,active FROM participants WHERE code=? AND type='AGENT'").get('A0'+(i+1))||null)}
function overview(db){const round=Math.max(1,db.prepare('SELECT round FROM agent_loop_state WHERE id=1').get().round),participants=people(db);const items=Array.from({length:7},(_,i)=>({tester:i+1,participant:participants[i],feature:schedule.features.find(f=>f.id===schedule.rounds[round-1].items[i].featureId)}));return {source:schedule.source,round,totalRounds:11,items,schedule}}
function transaction(db,fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}
function next(db,input,actor,audit){return transaction(db,()=>{const view=overview(db);if(input.round!==view.round)fail('Round changed. Refresh before advancing.');const round=view.round===schedule.rounds.length?1:view.round+1;db.prepare('UPDATE agent_loop_state SET round=? WHERE id=1').run(round);audit(actor,'NEXT_LOOP_ROUND','AGENT_LOOP',round,schedule.source);return {round}})}
function back(db,input,actor,audit){return transaction(db,()=>{const view=overview(db);if(input.round!==view.round)fail('Round changed. Refresh before advancing.');if(view.round===1)fail('Already on first round.');const round=view.round-1;db.prepare('UPDATE agent_loop_state SET round=? WHERE id=1').run(round);audit(actor,'BACK_LOOP_ROUND','AGENT_LOOP',round,schedule.source);return {round}})}
module.exports={setup,overview,next,back};
