'use strict';
const caseUI=require('../public/case-ui');

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=value=>Math.max(0,Number(value)||0);
const label=value=>String(value??'').replaceAll('_',' ');
const csrf=user=>'<input type="hidden" name="_csrf" value="'+esc(user.csrf)+'">';
const status=value=>'<span class="status '+esc(value)+'">'+esc(label(value))+'</span>';
const productionStatus=value=>{const key=value||'PENDING',names={PASSED:'Passed',FAILED:'Failed',PENDING:'Pending',DEPENDENCY:'Dependency',NOT_EXECUTED:'Not Executed',NCFL:'NCFL',PRODUCTION_TEST:'Production Test',PRODUCTION_BUG:'Production Bug',NOT_APPLICABLE:'N/A',IN_PROGRESS:'In Progress',STAGE_TEST:'Stage Test'};return '<span class="status production-status '+esc(key)+'">'+esc(names[key]||label(key))+'</span>'};
const tvStatus=value=>'<span class="tv-participant-status '+esc(value.toLowerCase())+'">'+esc(value)+'</span>';
const channel=value=>'<span class="channel-badge">'+esc(value||'Uncategorized')+'</span>';
const errorTargets=' hx-target-4*="#action-message" hx-target-5*="#action-message"';

function home(role){return role==='ADMIN'?'/admin':role==='OBSERVER'?'/my-tests':role==='AGENT'?'/tv/agents':role==='BRANCH'?'/tv/branches':role==='TECH'?'/qa':'/tv/management'}
function nav(user,tv){
  if(!user)return '';
  const normal=[['/my-tests','My Tests'],['/admin','Administration'],['/qa','QA & Technical'],['/tv/management','TV Screens']];
  if(user.role==='OBSERVER')normal.splice(0,normal.length,['/observer','Observer'],['/my-tests','My Tests'],['/qa','QA & Technical'],['/tv/management','TV Screens']);
  const allTv=[['/tv/management','Management TV'],['/tv/agents','Agent TV'],['/tv/branches','Branch TV']];
  const links=tv?(user.role==='AGENT'?allTv.slice(1,2):user.role==='BRANCH'?allTv.slice(2,3):['ADMIN','QA_LEAD','MANAGER','DISPLAY','OBSERVER'].includes(user.role)?allTv:[]):normal;
  return '<nav '+(!tv?'id="workspace-navigation" ':'')+'class="'+(tv?'tv-tabs':'')+'" aria-label="'+(tv?'TV screens':'Workspace')+'">'+links.map(([href,text])=>'<a href="'+href+'"'+(href===user.path?' aria-current="page"':'')+'>'+text+'</a>').join('')+'</nav>';
}
function document({title,user,path,content,tv=false,demo=process.env.DEMO_MODE==='true'}){
  if(!user)return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in | Wing Bank</title><link rel="preload" href="/brand-background.png" as="image"><link rel="stylesheet" href="/brand.css"><link rel="stylesheet" href="/style.css"><script src="/request-loading.js" defer></script><script src="/vendor/htmx-2.0.10.min.js" defer></script><script src="/vendor/htmx-ext-response-targets-2.0.4.js" defer></script></head><body hx-boost="true" hx-ext="response-targets"><main class="login-shell">'+content+'</main><script src="/htmx-client.js" defer></script></body></html>';
  const mainAttrs=tv&&demo?' hx-get="'+esc(path)+'" hx-trigger="every 10s" hx-swap="innerHTML"':tv?' hx-ext="sse" sse-connect="/api/events" hx-get="'+esc(path)+'" hx-trigger="sse:refresh" hx-swap="innerHTML"':'';
  user.path=path.split('?')[0];const brand='<div class="brand-identity"><img class="brand-logo" src="/wing-logo.svg" width="1000" height="335" alt="Wing Bank"><span class="brand-divider" aria-hidden="true"></span><div class="brand-copy"><p class="eyebrow">Production Test Center</p><h1 class="brand">'+esc(title)+'</h1></div></div>',homeLink='<a class="btn header-action alt home-button" href="'+home(user.role)+'" aria-label="Home" title="Home"><svg class="home-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9M9 20v-7h6v7"/></svg></a>',logout='<form action="/actions/logout" method="post" hx-post="/actions/logout">'+csrf(user)+'<button class="header-action">Logout</button></form>';
  const leading=tv?(user.path==='/tv/management'?'<button type="button" class="header-action back-icon alt" data-back aria-label="Go back" title="Go back">←</button>':''):homeLink;
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="'+esc(user.csrf)+'"><title>'+esc(title)+' | Wing Bank</title><link rel="preload" href="/brand-background.png" as="image"><link rel="stylesheet" href="/brand.css"><link rel="stylesheet" href="/style.css"><script src="/request-loading.js" defer></script><script src="/vendor/htmx-2.0.10.min.js" defer></script><script src="/vendor/htmx-ext-response-targets-2.0.4.js" defer></script>'+(tv?'<script src="/vendor/htmx-ext-sse-2.2.4.js" defer></script>':'')+'</head><body class="'+(tv?'tv tv-'+esc(path.split('/')[2]):'')+'" hx-boost="true" hx-ext="response-targets"><div class="shell"><header class="site-header">'+leading+brand+(tv?nav(user,true)+homeLink+(demo?'<span class="live" role="status">UPDATES EVERY 10s</span>':'<span class="live" data-connection="connecting" role="status">CONNECTING</span>'): '<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="workspace-navigation">Menu</button>'+nav(user,false)+'<span class="workspace-label">INTERNAL WORKSPACE</span>')+logout+'</header><main id="content"'+mainAttrs+'>'+(demo&&!process.env.TURSO_DATABASE_URL?'<p class="notice" role="status">DEMO · Temporary data. Uploads and changes may reset when server instances restart.</p>':'')+content+'</main></div><div id="action-message" aria-live="polite"></div><script src="/htmx-client.js" defer></script></body></html>';
}
function login(message=''){return '<section class="card login"><img class="brand-logo" src="/wing-logo.svg" width="1000" height="335" alt="Wing Bank"><p class="eyebrow">Internal testing workspace</p><h1>Production Test Center</h1><p class="muted">Sign in with your assigned internal account.</p><form action="/actions/login" method="post" hx-post="/actions/login" hx-target="#login-message"'+errorTargets+'><label>Username<input name="username" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button>Sign in</button><div id="login-message" role="alert">'+message+'</div></form></section>'}
function report(title,data,empty){const sums=[['Assigned',data.assignedCases],['Submitted',data.submittedCases],['Testing',data.testingParticipants],['Done',data.doneParticipants]];return '<section class="card management-participant-report"><h2>'+title+'</h2><div class="management-report-summary">'+sums.map(x=>'<div><small>'+x[0]+'</small><b>'+n(x[1])+'</b></div>').join('')+'</div><div class="management-report-list">'+(data.items.map(p=>'<div class="management-report-row"><div><b>'+esc(p.code+' · '+p.name)+'</b><small>'+n(p.activeChannels)+' channel'+(n(p.activeChannels)===1?'':'s')+' · '+n(p.submitted)+' / '+n(p.assigned)+' submitted</small></div><strong>'+n(p.progressPercent)+'%</strong>'+tvStatus(p.status)+'</div>').join('')||'<p class="muted">'+empty+'</p>')+'</div></section>'}
function management(data,agents,branches){const pct=data.total?Math.round(data.completed*100/data.total):0,metrics=[['Completion',pct+'%',''],['Assigned tests',data.total,''],['Passed',data.completed,'green'],['Failed',data.failed,'red'],['Blocked',data.blocked,'purple'],['Resolved',data.resolved,'blue'],['Pending',data.pending,''],['Channels',data.channels.length,'']],target=new Date(data.goLive).toLocaleString('en-GB',{timeZone:'Asia/Phnom_Penh',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}),rows=data.channels.map(x=>'<tr class="'+(x.failed+x.blocked?'risk-row':'')+'"><th>'+esc(x.channel)+'</th><td>'+n(x.total)+'</td><td>'+n(x.completed)+'</td><td>'+n(x.failed)+'</td><td>'+n(x.blocked)+'</td><td>'+n(x.resolved)+'</td><td>'+n(x.pending)+'</td><td><b>'+n(x.completionPercent)+'%</b></td><td>'+n(x.financePending)+'</td></tr>').join('');return '<section class="page-context" aria-label="Go-live countdown"><div><span class="launch-label">Go-live · '+esc(target)+' ICT</span><p class="sub">Assignment status by delivery channel · Updated '+esc(new Date(data.lastUpdated).toLocaleString('en-GB'))+'</p></div><div class="countdown" data-countdown="'+esc(data.goLive)+'" aria-label="Time until go-live"></div></section><section class="metrics" aria-label="Testing totals">'+metrics.map(x=>'<div class="metric"><small>'+x[0]+'</small><b class="'+(x[2]?'text-'+x[2]:'')+'">'+esc(x[1])+'</b></div>').join('')+'</section><section class="card channel-overview"><h2>Channel QA / result overview</h2><div class="table-scroll"><table><thead><tr><th>Channel</th><th>Assigned</th><th>Passed</th><th>Failed</th><th>Blocked</th><th>Resolved</th><th>Pending</th><th>Completion</th><th>Finance pending</th></tr></thead><tbody>'+rows+'</tbody></table></div>'+(!rows?'<p class="form muted">No real test cases have been imported yet.</p>':'')+'</section><section class="management-participant-reports" aria-label="Agent and Branch reports">'+report('Agent Report',agents,'No assigned Agent data')+report('Branch Report',branches,'No assigned Branch data')+'</section>'}
function participantTv(type,data,privateView){const plural=type==='AGENT'?'agents':'branch teams';return '<section class="participant-tv-context"><div><b>'+(privateView?'Your testing progress':'All assigned '+plural)+'</b><p>Updated '+esc(new Date(data.lastUpdated).toLocaleString('en-GB'))+'</p></div></section><section class="metrics participant-tv-metrics" aria-label="TV totals">'+[['Assigned cases',data.assignedCases],['Submitted cases',data.submittedCases],['Testing participants',data.testingParticipants],['Done participants',data.doneParticipants]].map(x=>'<div class="metric"><small>'+x[0]+'</small><b>'+n(x[1])+'</b></div>').join('')+'</section><section class="participant-tv-list '+(privateView?'private-view':type==='AGENT'?'agent-grid':'branch-grid')+'" aria-label="Participant progress">'+(data.items.map(p=>'<article class="card participant-tv-card"><div class="participant-tv-main"><span class="station-code">'+esc(p.code)+'</span><div><h2>'+esc(p.name)+'</h2><p>'+n(p.activeChannels)+' active channel'+(n(p.activeChannels)===1?'':'s')+'</p></div></div><div class="participant-tv-result"><b>'+n(p.progressPercent)+'%</b>'+tvStatus(p.status)+'<small>'+n(p.submitted)+' / '+n(p.assigned)+' submitted</small></div><progress value="'+n(p.submitted)+'" max="'+Math.max(1,n(p.assigned))+'" aria-label="'+esc(p.code)+' submission progress"></progress></article>').join('')||'<article class="card participant-tv-empty"><h2>No assigned test cases</h2><p>Participants appear here after test cases are assigned.</p></article>')+'</section>'}
function channelFilter(path,channels,selected,assignable=false){return '<form method="get" action="'+path+'" hx-get="'+path+'" hx-trigger="change" hx-target="#content" hx-push-url="true"><label class="channel-filter">Channel<select name="channel"><option value="">All channels</option>'+channels.map(x=>'<option value="'+esc(x)+'"'+(x===selected?' selected':'')+'>'+esc(x)+'</option>').join('')+'</select></label>'+(path==='/admin'?'<label>Cases<select name="status"><option value="">All cases</option><option value="NOT_STARTED"'+(assignable?' selected':'')+'>Assignable only</option></select></label>':'')+'<button class="alt">Apply</button></form>'}
function myTestsFilters(data,user,selected,participantId){
 const form=channelFilter('/my-tests',data.availableChannels,selected);
 const extra=(participantId?'<input type="hidden" name="participantId" value="'+esc(participantId)+'">':'');
 if(user.role!=='OBSERVER')return form.replace('</form>',extra+'</form>');
 return form.replace('<form ', '<form class="assignment-filters" ').replace('<button class="alt">Apply</button>',caseUI.observerControls(data)+'<button class="alt">Apply</button><a class="btn alt" href="'+esc(caseUI.clearHref(data.filters))+'">Clear filters</a>').replace('</form>',extra+'</form>');
}
function myTests(data,user,selected,participantId=''){return '<section class="page-context"><div><h2>Priority queue</h2><p class="sub">'+(data.sortBy&&data.sortBy!=='default'?'Cases follow selected sort order.':'Cases are ordered by channel and priority.')+'</p></div>'+myTestsFilters(data,user,selected,participantId)+'</section><section class="card"><div class="rows">'+(data.items.map(x=>{let action='<span class="muted">Awaiting next step</span>';if(x.status==='NOT_STARTED')action='<form method="post" action="/actions/assignments/'+n(x.id)+'/start" hx-post="/actions/assignments/'+n(x.id)+'/start" hx-target="#content"'+errorTargets+'>'+csrf(user)+caseUI.returnInput('/my-tests',data.filters||{})+'<button>Start</button></form>';else if(['IN_PROGRESS','RETESTING'].includes(x.status))action='<form class="qa-submit" method="post" action="/actions/assignments/'+n(x.id)+'/submit" hx-post="/actions/assignments/'+n(x.id)+'/submit" hx-target="#content"'+errorTargets+'>'+csrf(user)+caseUI.returnInput('/my-tests',data.filters||{})+'<label>Result<select name="reportedResult" required><option value="">Select result</option><option value="PASSED">Passed</option><option value="FAILED">Failed</option><option value="BLOCKED">Blocked</option></select></label><label>Note<textarea name="submissionNote" rows="3" maxlength="2000" placeholder="Add execution details for QA"></textarea></label><button>Submit to QA</button></form>';else if(x.status==='PENDING_QA')action='<div class="submission-summary"><b>Reported '+esc(label(x.reported_result))+'</b>'+(x.submission_note?'<p>'+esc(x.submission_note)+'</p>':'')+'<span class="muted">Waiting for QA verification</span></div>';const details=caseUI.detailsHtml(x);return '<div id="assignment-'+n(x.id)+'" class="row case-row"><div>'+(user.role==='OBSERVER'?'<p class="muted">'+esc(x.code+' · '+x.name)+'</p>':'')+'<div>'+channel(x.channel)+' '+status(x.status)+'</div><b>'+esc(caseUI.caseLabel(x)+' · '+x.title)+'</b><details><summary>Test details</summary><p>'+esc(x.expected_result)+'</p><div class="detail-grid" data-source-details="true">'+details+'</div></details></div><span>Priority '+n(x.priority)+'</span>'+action+'</div>'}).join('')||'<p class="form muted">'+(user.role==='OBSERVER'?'No tests match selected filters.':'No test cases assigned.')+'</p>')+'</div></section>'}
function qa(data,submissions,user,selected){const editable=['ADMIN','QA_LEAD','TECH','OBSERVER'].includes(user.role),canReview=['ADMIN','QA_LEAD','OBSERVER'].includes(user.role),allowed=['ASSIGNED','INVESTIGATING','FIX_IN_PROGRESS','READY_FOR_QA_REVIEW',...(user.role==='TECH'?[]:['READY_FOR_RETEST','RETESTING','RESOLVED','REOPENED'])],pending=submissions.items.map(x=>'<div class="row qa-review-row"><div>'+channel(x.channel)+' '+status(x.reported_result)+'<b>'+esc(caseUI.caseLabel(x)+' · '+x.participant_code+' · '+x.participant_name)+'</b><div class="muted">'+esc(x.title)+'</div><p>'+esc(x.submission_note||'No note provided')+'</p></div>'+(canReview?'<form class="qa-review-controls" method="post" action="/actions/assignments/'+n(x.id)+'/review" hx-post="/actions/assignments/'+n(x.id)+'/review" hx-target="#content"'+errorTargets+'>'+csrf(user)+'<label>QA remark<input name="qaRemark" placeholder="Optional review note"></label><div class="review-actions"><button name="decision" value="APPROVE">Approve</button><button name="decision" value="RETURN" class="alt">Return to tester</button></div></form>':'<span class="muted">QA approval required</span>')+'</div>').join('');return '<section class="page-context"><div><h2>QA verification</h2><p class="sub">Agent and branch results remain pending until QA approval.</p></div>'+channelFilter('/qa',submissions.availableChannels,selected)+'</section><section class="card"><h2>Pending verification</h2><div class="rows">'+(pending||'<p class="form muted">No submissions awaiting QA.</p>')+'</div></section><section class="card"><h2>Test Cases</h2><div class="rows">'+(data.items.map(x=>'<div class="row defect-row"><div>'+channel(x.channel)+'<p class="saved-status">Saved status: '+status(x.status)+'</p>'+'<b>'+esc(caseUI.caseLabel(x)+' · '+x.participant_code)+'</b><div class="muted">'+esc(x.title)+'</div><div class="muted">Tester: '+esc(x.tester||'Not recorded')+' · Finance: '+esc(x.finance_status||'Not recorded')+'</div>'+(x.qa_remark?'<p>'+esc(x.qa_remark)+'</p>':'')+(x.jira_link?'<a href="'+esc(x.jira_link)+'" target="_blank" rel="noopener">Open Jira</a>':'')+'</div>'+(editable?'<form class="defect-actions" method="post" action="/actions/defects/'+n(x.id)+'" hx-post="/actions/defects/'+n(x.id)+'" hx-target="#content"'+errorTargets+'>'+csrf(user)+'<select name="status">'+allowed.map(s=>'<option value="'+s+'"'+(s===x.status?' selected':'')+'>'+esc(label(s))+'</option>').join('')+'</select><input name="owner" value="'+esc(x.owner)+'" placeholder="Owner"><button>Update</button></form>':status(x.status))+'</div>').join('')||'<p class="form muted">No defects to display.</p>')+'</div></section>'}
function legacyAdmin(data,user){
  const participants=data.participants,active=participants.filter(x=>x.active),options=active.map(x=>'<option value="'+n(x.id)+'">'+esc(x.code+' · '+x.name)+'</option>').join(''),query=(page)=>'/admin?'+new URLSearchParams({...(data.selectedChannel?{channel:data.selectedChannel}:{}),...(data.assignable?{status:'NOT_STARTED'}:{}),page:String(page)}),pages=Math.max(1,Math.ceil(data.cases.total/data.cases.limit));
  const channelRows=data.dashboard.channels.map(x=>'<tr><th>'+esc(x.channel)+'</th><td>'+n(x.total)+'</td><td>'+n(x.completed)+'</td><td>'+n(x.failed)+'</td><td>'+n(x.pending)+'</td></tr>').join('');
  const caseRows=data.cases.items.map(x=>{const assignable=x.assignment_status==='NOT_STARTED';return '<tr><td>'+(assignable?'<input form="bulk-form" type="checkbox" name="caseIds" value="'+n(x.id)+'">':'')+'</td><td>'+esc(x.source_case_id||x.case_code)+'</td><td>'+channel(x.channel)+'</td><td>'+esc(x.title)+'</td><td>Priority '+n(x.priority)+'</td><td>'+(assignable?'<form method="post" action="/actions/test-cases/'+n(x.id)+'/assignment" hx-post="/actions/test-cases/'+n(x.id)+'/assignment" hx-target="#content"'+errorTargets+'>'+csrf(user)+'<select name="participantId" required>'+options+'</select><button>Assign</button></form>':status(x.assignment_status))+'</td><td>'+status(x.production_status)+'</td></tr>'}).join('');
  const users=data.users.map(x=>'<article class="person"><b>'+esc(x.username+' · '+x.display_name)+'</b><small>'+esc(x.role+' · '+(x.active?'Active':'Inactive'))+'</small><form method="post" action="/actions/users/'+n(x.id)+'/active" hx-post="/actions/users/'+n(x.id)+'/active" hx-target="#content"'+errorTargets+'>'+csrf(user)+'<input type="hidden" name="active" value="'+(x.active?'0':'1')+'"><button class="alt">'+(x.active?'Deactivate':'Activate')+'</button></form></article>').join('')||'<p class="form muted">No Manager or Display accounts.</p>';
  return '<div class="grid admin-grid"><section class="card"><h2>Create agent or branch team</h2><form method="post" action="/actions/participants" hx-post="/actions/participants" hx-target="#content"'+errorTargets+'>'+csrf(user)+'<input name="code" placeholder="A01 or B01" required><input name="name" placeholder="Name" required><select name="type"><option>AGENT</option><option>BRANCH</option></select><input name="observer" placeholder="Observer"><button>Create participant</button></form></section><section class="card"><h2>Create login account</h2><form method="post" action="/actions/users" hx-post="/actions/users" hx-target="#content"'+errorTargets+'>'+csrf(user)+'<input name="username" placeholder="Username" required><input name="displayName" placeholder="Display name" required><select name="role"><option>MANAGER</option><option>DISPLAY</option><option>AGENT</option><option>BRANCH</option></select><select name="participantId"><option value="">No participant</option>'+options+'</select><input type="password" name="password" required><button>Create account</button></form></section><section class="card full channel-summary"><h2>Channel import summary</h2><div class="table-scroll"><table><thead><tr><th>Channel</th><th>Assigned</th><th>Completed</th><th>Failed</th><th>Pending</th></tr></thead><tbody>'+channelRows+'</tbody></table></div></section><section class="card full"><div class="section-heading"><h2>Test case assignments</h2>'+channelFilter('/admin',data.dashboard.availableChannels,data.selectedChannel,data.assignable)+'</div><form id="bulk-form" method="post" action="/actions/assignments/bulk" hx-post="/actions/assignments/bulk" hx-target="#content"'+errorTargets+'>'+csrf(user)+'<select name="participantId" required><option value="">Assign selected to…</option>'+options+'</select><button>Assign selected</button></form><div class="table-scroll"><table><thead><tr><th></th><th>Case ID</th><th>Channel</th><th>Scenario</th><th>Priority</th><th>Assignment</th><th>Status</th></tr></thead><tbody>'+caseRows+'</tbody></table></div><nav class="pagination">'+(data.cases.page>1?'<a href="'+query(data.cases.page-1)+'">Previous</a>':'')+'<span>Page '+n(data.cases.page)+' / '+n(pages)+'</span>'+(data.cases.page<pages?'<a href="'+query(data.cases.page+1)+'">Next</a>':'')+'</nav></section><section class="card full"><h2>Manager and display accounts</h2><div class="people">'+users+'</div></section></div>'
}

function admin(data,user){
 const people=data.participants,active=people.filter(x=>x.active),opts=active.map(x=>`<option value="${n(x.id)}">${esc(x.code+' · '+x.name)}</option>`).join(''),accountOpts=active.map(x=>`<option value="${n(x.id)}">${esc(x.code+' · '+x.name+' ('+x.type+')')}</option>`).join(''),pages=Math.max(1,Math.ceil(data.cases.total/data.cases.limit)),href=page=>'/admin?'+new URLSearchParams({...(data.selectedChannel?{channel:data.selectedChannel}:{}),...(data.assignable?{status:'NOT_STARTED'}:{}),...(data.selectedSheet?{sheet:data.selectedSheet}:{}),...(data.selectedPriority?{priority:data.selectedPriority}:{}),...(data.sortBy?{sortBy:data.sortBy,orderBy:data.orderBy}:{}),page});
 const channels=data.dashboard.channels.map(x=>`<tr><th>${esc(x.channel)}</th><td>${n(x.total)}</td><td>${n(x.completed)}</td><td>${n(x.failed)}</td><td>${n(x.pending)}</td></tr>`).join('');
 const cases=data.cases.items.map(x=>{const can=x.assignment_status==='NOT_STARTED',id=x.source_case_id||x.case_code,selected=active.map(p=>`<option value="${n(p.id)}"${p.id===x.participant_id?' selected':''}>${esc(p.code+' · '+p.name)}</option>`).join('');return `<tr><td>${can?`<label class="case-select-hit"><input form="bulk-form" class="case-select" type="checkbox" name="caseIds" data-current-tester="${x.participant_id?esc(caseUI.caseLabel(x)+' → '+x.participant_code+' · '+x.participant_name):''}" value="${n(x.id)}" aria-label="Select ${esc(caseUI.caseLabel(x))}"></label>`:''}</td><td><b>${esc(id)}</b>${(x.subcategory||x.source_sheet)?`<small class="case-subcategory">${esc(x.subcategory||x.source_sheet)}</small>`:''}</td><td>${channel(x.channel)}</td><td>${esc(x.title)}</td><td class="assignment-priority">${n(x.priority)}</td><td class="assignment-agent">${can?`<form method="post" data-assignment-confirm="${x.participant_id?esc(caseUI.caseLabel(x)+' → '+x.participant_code+' · '+x.participant_name):''}" action="/actions/test-cases/${n(x.id)}/assignment" hx-post="/actions/test-cases/${n(x.id)}/assignment" hx-target="#content"${errorTargets}>${csrf(user)+caseUI.returnInput('/admin',data.filters||{})}<select name="participantId" required>${selected}</select><button>Assign</button></form>`:`<span>${esc((x.participant_code||'Unassigned')+(x.participant_name?' · '+x.participant_name:''))}</span>`}</td><td class="assignment-status">${productionStatus(x.production_status)}</td></tr>`}).join('');
 const users=data.users.map(x=>`<article class="person"><b>${esc(x.username+' · '+x.display_name)}</b><small>${esc(x.role+' · '+(x.active?'Active':'Inactive'))}</small><form method="post" action="/actions/users/${n(x.id)}/active" hx-post="/actions/users/${n(x.id)}/active" hx-target="#content"${errorTargets}>${csrf(user)+caseUI.returnInput('/admin',data.filters||{})}<input type="hidden" name="active" value="${x.active?'0':'1'}"><button class="btn alt">${x.active?'Deactivate':'Activate'}</button></form></article>`).join('')||'<p class="form muted">No manager or display accounts.</p>';
 const filters=`<form class="assignment-filters" method="get" action="/admin" hx-get="/admin" hx-trigger="change" hx-target="#content" hx-push-url="true"><label>Channel<select name="channel"><option value="">All channels</option>${data.dashboard.availableChannels.map(x=>`<option value="${esc(x)}"${x===data.selectedChannel?' selected':''}>${esc(x)}</option>`).join('')}</select></label><label>Sheet Name<select name="sheet"><option value="">All sheets</option>${data.availableSheets.map(x=>`<option value="${esc(x)}"${x===data.selectedSheet?' selected':''}>${esc(x)}</option>`).join('')}</select></label><label>Priority<select name="priority"><option value="">All priorities</option>${[1,2,3,4].map(x=>`<option value="${x}"${String(x)===data.selectedPriority?' selected':''}>Priority ${x}</option>`).join('')}</select></label><label>Cases<select name="status"><option value="">All cases</option><option value="NOT_STARTED"${data.assignable?' selected':''}>Assignable only</option></select></label>${caseUI.sortControls(data)}<button class="alt">Apply</button></form>`,start=n(data.cases.total?data.cases.offset+1:0),end=n(Math.min(data.cases.offset+data.cases.items.length,data.cases.total));
 return `<div class="grid admin-grid"><section class="card"><h2>Create agent or branch team</h2><form class="form" method="post" action="/actions/participants" hx-post="/actions/participants" hx-target="#content"${errorTargets}>${csrf(user)+caseUI.returnInput('/admin',data.filters||{})}<label>Participant code<input name="code" placeholder="A01 or B01" required><small class="field-help">Example: A01 for an Agent or B01 for a Branch. Use A/B followed by 2–4 digits.</small></label><label>Name<input name="name" required><small class="field-help">Any non-empty name is accepted.</small></label><label>Team type<select name="type"><option value="AGENT">Agent</option><option value="BRANCH">Branch</option></select></label><label>Observer name<input name="observer"></label><button>Create participant</button></form></section>
 <section class="card"><h2>Import production sample · Excel</h2><form class="form" method="post" enctype="multipart/form-data" action="/actions/import-production" hx-post="/actions/import-production" hx-encoding="multipart/form-data" hx-target="#content"${errorTargets}>${csrf(user)+caseUI.returnInput('/admin',data.filters||{})}<label>Channel name<input name="channel" placeholder="e.g. WCX POS" maxlength="100" required></label><label>Production workbook<input name="workbook" type="file" accept=".xlsx" required></label><p class="muted">All cases use entered channel. Worksheet names become subcategories. Other channels and saved testing results remain unchanged.</p><button>Validate and import</button></form></section>

 <section class="card"><h2>Create login account</h2><form class="form" method="post" action="/actions/users" hx-post="/actions/users" hx-target="#content"${errorTargets}>${csrf(user)+caseUI.returnInput('/admin',data.filters||{})}<label>Username<input name="username" required></label><label>Display name<input name="displayName" required></label><label>Role<select name="role"><option value="MANAGER">Manager</option><option value="DISPLAY">TV display</option><option value="AGENT">Agent</option><option value="BRANCH">Branch</option><option value="OBSERVER">Observer</option></select></label><label>Linked participant<select name="participantId"><option value="">Required for Agent/Branch; optional for Observer</option>${accountOpts}</select></label><label>Temporary password<input type="password" name="password" required><small class="field-help">Any non-empty password is accepted.</small></label><button>Create account</button></form></section>
 <section class="card full channel-summary"><h2>Channel import summary</h2><p class="table-scroll-hint">Scroll horizontally to view all columns.</p><div class="table-scroll" role="region" tabindex="0" aria-label="Channel import summary table"><table><thead><tr><th>Channel</th><th>Assigned</th><th>Completed</th><th>Failed</th><th>Pending</th></tr></thead><tbody>${channels}</tbody></table></div></section>
 <section class="card full"><div class="section-heading"><h2>Test case assignments</h2>${filters}</div><form id="bulk-form" class="bulk-assignment" method="post" action="/actions/assignments/bulk" hx-post="/actions/assignments/bulk" hx-target="#content"${errorTargets}>${csrf(user)+caseUI.returnInput('/admin',data.filters||{})}<label>Assign selected cases to<select id="bulk-agent" name="participantId" required><option value="">Select agent</option>${opts}</select></label><button>Bulk assign (<span id="selected-count">0</span>)</button></form><p class="table-scroll-hint">Scroll horizontally to view all columns.</p><div class="table-scroll" role="region" tabindex="0" aria-label="Test case assignments table"><table class="assignment-table"><thead><tr><th><label class="case-select-hit"><input id="select-page" type="checkbox" aria-label="Select all displayed assignable cases"></label></th><th>Case ID</th><th>Channel</th><th>Scenario</th><th class="assignment-priority">Priority</th><th class="assignment-agent">Assigned agent</th><th class="assignment-status">Status / action</th></tr></thead><tbody>${cases}</tbody></table></div><nav class="pagination" aria-label="Test case pages"><span>${start}–${end} of ${n(data.cases.total)}</span>${data.cases.page>1?`<a class="btn alt" href="${href(data.cases.page-1)}">Previous</a>`:''}${data.cases.page<pages?`<a class="btn alt" href="${href(data.cases.page+1)}">Next</a>`:''}</nav></section>
 <section class="card full"><h2>Manager and display accounts</h2><div class="people">${users}</div></section></div>`;
}

function observer(testers,data,user,params){
 const selected=params.get('participantId')||'',selectedChannel=params.get('channel')||'';
 const options=testers.items.filter(p=>p.active).map(p=>`<option value="${n(p.id)}"${String(p.id)===selected?' selected':''}>${esc(p.code+' · '+p.name)}</option>`).join('');
 const cards=testers.items.map(p=>`<article class="person"><b>${esc(p.code+' · '+p.name)}</b><small>${esc(p.type)}${p.active?'':' · Inactive'}</small><p>${n(p.completed)} / ${n(p.assigned)} completed · ${p.assigned?Math.round(p.completed/p.assigned*100):0}%</p>${p.assigned?'':'<p>No assigned tests.</p>'}<a href="/my-tests?participantId=${n(p.id)}">View tests</a><form method="post" action="/actions/observer/testers/${n(p.id)}/unlink" hx-post="/actions/observer/testers/${n(p.id)}/unlink" hx-target="#content"${errorTargets} hx-confirm="${esc('Unlink '+p.code+' · '+p.name+'? Observer access will be removed.')}" data-confirm="${esc('Unlink '+p.code+' · '+p.name+'? Observer access will be removed.')}">${csrf(user)}<label class="unlink-confirm"><input type="checkbox" name="confirmed" value="1" required> Confirm unlink ${esc(p.code)}</label><button class="alt">Unlink</button></form></article>`).join('');
 const rows=data.items.map(x=>`<tr><td><a href="/my-tests?participantId=${n(x.participant_id)}#assignment-${n(x.id)}">${esc(x.source_case_id||x.case_code)}</a></td><td>${esc(x.title)}</td><td>${esc(x.code+' · '+x.name)}</td><td>${channel(x.channel)}</td><td>${n(x.priority)}</td><td>${status(x.status)}</td><td>${x.reported_result?status(x.reported_result):'—'}</td></tr>`).join('');
 const pages=Math.max(1,Math.ceil(data.total/data.limit)),href=page=>'/observer?'+new URLSearchParams({...(selected?{participantId:selected}:{}),...(selectedChannel?{channel:selectedChannel}:{}),page:String(page)});
 return `<div class="grid observer-grid"><section class="card"><h2>Link tester</h2><form class="form" method="post" action="/actions/observer/link" hx-post="/actions/observer/link" hx-target="#content"${errorTargets}>${csrf(user)}<label>Unassigned Agent or Branch<select name="participantId" required><option value="">Select tester</option>${testers.available.map(p=>`<option value="${n(p.id)}">${esc(p.code+' · '+p.name+' ('+p.type+')')}</option>`).join('')}</select></label><button${testers.available.length?'':' disabled'}>Link tester</button>${testers.available.length?'':'<p>No unassigned testers available.</p>'}</form></section><section class="card"><h2>Linked testers</h2><div class="people">${cards||'<p class="form muted">No linked testers. Link testers to manage their tests.</p>'}</div></section><section class="card full"><h2>Assigned tests</h2><form class="observer-filters form" method="get" action="/observer" hx-get="/observer" hx-target="#content" hx-push-url="true"><label>Tester<select name="participantId"> <option value="">All linked testers</option>${options}</select></label><label>Channel<select name="channel"><option value="">All channels</option>${data.availableChannels.map(c=>`<option${c===selectedChannel?' selected':''}>${esc(c)}</option>`).join('')}</select></label><button>Filter</button></form><div class="table-scroll" role="region" tabindex="0" aria-label="Observer assigned tests"><table><thead><tr><th>Case ID</th><th>Scenario</th><th>Tester</th><th>Channel</th><th>Priority</th><th>Workflow status</th><th>Reported result</th></tr></thead><tbody>${rows||'<tr><td colspan="7">No assigned tests.</td></tr>'}</tbody></table></div><nav class="pagination" aria-label="Assigned test pages">${data.page>1?`<a href="${esc(href(data.page-1))}">Previous</a>`:''}<span>Page ${n(data.page)} / ${n(pages)} · ${n(data.total)} tests</span>${data.page<pages?`<a href="${esc(href(data.page+1))}">Next</a>`:''}</nav></section></div>`;
}

module.exports={document,login,management,participantTv,myTests,qa,admin,observer,esc};
